Margin trading interface adjustments
DistributedCollective/Sovryn-frontend pull request #1025
Opened 2021-05-04 13:12 UTC by tiltom

2021-05-04 13:32 UTC, creed-victor requested changes
Sorry made a mistake with the request, we needed `/` to change with ` - ` :)
Change should be done in the `RenderTradingPairName` component/helper

2021-05-05 10:55 UTC, tiltom commented
> Sorry made a mistake with the request, we needed `/` to change with `-` :)
> Change should be done in the `RenderTradingPairName` component/helper

And should I left USDT as USDT or change it back to rUSDT?

2021-05-05 12:05 UTC, tiltom commented
Updated.

2021-05-05 12:13 UTC, creed-victor approved these changes

2021-05-05 12:14 UTC, merged