Feat/redesign updates
DistributedCollective/Sovryn-frontend pull request #1050
Opened 2021-05-08 23:12 UTC by soulBit

- Add Highcharts for Lending page APR
- Update Tradingview chart attribution text color
- Update rounded corner size for Spot/Margin Trade pages
- Restore email notification form to Margin Trade page

2021-05-09 01:11 UTC, bitcoinuser commented
Hi,

Please add the strings to be able to translate to PT-BR

2021-05-09 01:22 UTC, bitcoinuser commented
I think https://github.com/DistributedCollective/Sovryn-frontend/issues/1043 could be fixed here.

2021-05-09 01:26 UTC, bitcoinuser commented
Hi,

I think the distance from white line and the date is small here:

![Captura de tela de 2021-05-08 22-21-43](https://user-images.githubusercontent.com/1178856/117557718-685f2100-b04c-11eb-9623-d1b30d9e72b0.png)

2021-05-09 23:49 UTC, bitcoinuser commented
Hi @soulBit, Suggestion: put the circles on top and remove the info from bottom

![Captura de tela de 2021-05-09 20-44-01](https://user-images.githubusercontent.com/1178856/117590916-167bd100-b108-11eb-9194-c93cb457517a.png)

2021-05-09 23:50 UTC, bitcoinuser commented
> Hi @soulBit, Suggestion: put the circles on top and remove the info from bottom
> 
> ![Captura de tela de 2021-05-09 20-44-01](https://user-images.githubusercontent.com/1178856/117590916-167bd100-b108-11eb-9194-c93cb457517a.png)

Or remove the text that is repeated from bottom and let only the circles.

2021-05-10 11:51 UTC, creed-victor requested changes

2021-05-10 11:51 UTC, creed-victor commented on src/app/containers/LendBorrowSovryn/components/CurrencyContainer/CurrencyRow.tsx
> +        'sovryn-border overflow-hidden tw-pb-0 tw-pt-1 lg:tw-pt-2 currency-container tw-mb-4 tw-text-muted',
```suggestion
        'sovryn-border tw-overflow-hidden tw-pb-0 tw-pt-1 lg:tw-pt-2 currency-container tw-mb-4 tw-text-muted',
```

2021-05-10 11:51 UTC, creed-victor commented on src/app/components/LoanTokenGraphs/index.tsx
> -// import styled from 'styled-components/macro';
i think `@vix/` packages can be removed from package.json too because they were used only for lending charts.

2021-05-11 09:54 UTC, merged