fix buttons #997
DistributedCollective/Sovryn-frontend pull request #1194
Opened 2021-05-27 14:24 UTC by pietro-maximoff

2021-05-27 15:10 UTC, tiltom approved these changes

2021-05-27 15:11 UTC, tiltom commented
The changes themselves are good but we have some other buttons as well (i.e. `ActionButton` that is used on Liquidity mining page) that needs adjustment.

![image](https://user-images.githubusercontent.com/14878713/119851335-9c708800-bf0e-11eb-965c-a35bae1da9bf.png)

2021-05-27 15:13 UTC, tiltom requested changes
The changes themselves are good but we have some other buttons as well (i.e. `ActionButton` that is used on Liquidity mining page) that needs adjustment.

![image](https://user-images.githubusercontent.com/14878713/119851335-9c708800-bf0e-11eb-965c-a35bae1da9bf.png)

2021-05-27 15:23 UTC, boltsr reviewed
LGTM!

2021-06-03 11:25 UTC, creed-victor approved these changes

2021-06-07 09:28 UTC, merged