Bug/1205-transak-fiat-receiver
DistributedCollective/Sovryn-frontend pull request #1324
Opened 2021-06-12 15:50 UTC by boltsr

fix transack issue

2021-06-14 07:18 UTC, grinry requested changes
You need to make sure that `actions.openFiatOnRamp` works same way as 
https://github.com/DistributedCollective/Sovryn-frontend/blob/6b909938dc661d81b4390631657728f8485e87f1/src/app/containers/FastBtcDialog/saga.ts#L45
to generate address and only then open transak widget.

With current changes you only open widget and it has no deposit address - so not usable for user.

2021-06-14 20:01 UTC, grinry requested changes

2021-06-14 20:01 UTC, grinry commented on src/app/containers/FastBtcDialog/slice.ts
>      },
I think it will not be used anymore, can be deleted

2021-06-15 05:26 UTC, creed-victor approved these changes

2021-06-15 05:44 UTC, merged