Initial commit
DistributedCollective/Sovryn-frontend pull request #1328
Opened 2021-06-14 14:40 UTC by tiltom

2021-06-15 05:42 UTC, creed-victor requested changes

2021-06-15 05:42 UTC, creed-victor commented on src/app/components/NetworkRibbon/component/DetectionScreen.tsx
> +              onClick={addRskMainnet}
```suggestion
              onClick={currentNetwork === 'mainnet' ? addRskMainnet : addRskTestnet}
```

2021-06-15 05:42 UTC, creed-victor commented on src/utils/metamaskHelpers.ts
> +      rpcUrls: ['https://public-node.rsk.co'],
```suggestion
      rpcUrls: ['https://mainnet.sovryn.app/rpc'],
```

2021-06-15 05:42 UTC, creed-victor commented on src/utils/metamaskHelpers.ts
> +      rpcUrls: ['https://public-node.testnet.rsk.co'],
```suggestion
      rpcUrls: ['https://testnet.sovryn.app/rpc'],
```

2021-06-15 05:42 UTC, creed-victor commented on src/utils/metamaskHelpers.ts
> +      chainName: 'RSK Mainnet',
```suggestion
      chainName: 'RSK',
```

2021-06-17 16:56 UTC, soulBit approved these changes

2021-06-17 17:38 UTC, creed-victor approved these changes

2021-06-18 07:57 UTC, merged