Convert RUSDT to XUSD
DistributedCollective/Sovryn-frontend pull request #1341
Opened 2021-06-15 14:22 UTC by tiltom

2021-06-16 08:55 UTC, grinry requested changes

2021-06-16 08:55 UTC, grinry commented on src/app/components/UserAssets/ConversionDialog.tsx
> +            {t(translations.userAssets.convertDialog.txFee)}: 0.0006{' '}
Use TxFeeCalculator component to calculate real fee

2021-06-16 08:55 UTC, grinry commented on src/app/hooks/portfolio/useConvertToXUSD.ts
> +        getContract('USDT_token').address,
Right now you are approving USDT token to be used by USDT token, spender must be babelfishAggregator here:

```suggestion
        getContract('babelfishAggregator').address,
```

2021-06-16 09:37 UTC, creed-victor commented
Do not merge to master until June 18th.

2021-06-16 09:47 UTC, grinry submitted a review, later dismissed

2021-06-16 10:25 UTC, grinry submitted a review, later dismissed

2021-06-18 09:16 UTC, soulBit submitted a review, later dismissed

2021-06-18 09:18 UTC, t-z-u commented
the launch of this has been delayed so could we please add the correct transaction window now it is not a rush to push

2021-06-21 09:12 UTC, soulBit approved these changes

2021-06-21 10:30 UTC, creed-victor approved these changes

2021-06-21 10:31 UTC, merged