Add and translate new strings to PT-BR
DistributedCollective/Sovryn-frontend pull request #142
Opened 2021-01-12 15:07 UTC by bitcoinuser

2021-01-12 16:40 UTC, creed-victor requested changes
@bitcoinuser hey, there is a missing comma ;)

2021-01-12 16:40 UTC, creed-victor commented on src/locales/pt_br/translation.json
> +      "amount": "Valor do empréstimo",
```suggestion
      "title": "Histórico",
      "amount": "Valor do empréstimo",
```

2021-01-13 12:42 UTC, bitcoinuser commented
Hi @creed-victor what is wrong with this PR? thanks

2021-01-13 15:27 UTC, creed-victor approved these changes

2021-01-13 15:27 UTC, merged