Bug/1298 wrong update build id
DistributedCollective/Sovryn-frontend pull request #1429
Opened 2021-07-05 16:00 UTC by ShynRou

Resolves #1298 

Added a version.json file to public that gets overwritten by the webpack build on production with the correct commit hash.
Used the version.json file to handle the when to show the update dialog.

Also made it possible to make a development build with the build script for testing purposes.

To test the new toast implementation, It's best to run `yarn run build:testnet` and `yarn run serve`, then change the version file in the build directory.

2021-07-14 12:03 UTC, tiltom requested changes

2021-07-14 14:26 UTC, ShynRou commented on scripts/build.js
>      console.log();
Wasn't my change, but removed it for cleanliness.

2021-07-14 14:27 UTC, ShynRou commented on src/app/components/ServiceWorkerToaster/index.tsx
>  interface Props {}
Removed it.

2021-07-14 14:28 UTC, ShynRou commented on src/app/components/ServiceWorkerToaster/index.tsx
> +  const fetchVersion = async () => {
yep just wrapped it and changed it to fetch like the TODO comment requested ^^

2021-07-14 15:03 UTC, tiltom commented on scripts/build.js
>      console.log();
I know it wasn't your change but it looked weird, thanks for removing :)

2021-07-14 15:04 UTC, tiltom submitted a review, later dismissed

2021-07-15 10:35 UTC, soulBit submitted a review, later dismissed
Tested locally and all works as expected, approving changes but let's wait for Victor to review before we merge this

2021-07-21 12:58 UTC, creed-victor submitted a review, later dismissed
Looks good

2021-07-23 10:16 UTC, merged