[Lend] - #1455
DistributedCollective/Sovryn-frontend pull request #1483
Opened 2021-07-15 05:43 UTC by pietro-maximoff

- Fix leftover dust issue
- Show full balance with 8 decimals for "Your Deposit" value
- Add tooltip for "Your Deposit", "Profit", and "Rewards" values

2021-07-15 09:40 UTC, soulBit approved these changes

2021-07-15 15:21 UTC, tiltom requested changes

2021-07-15 15:21 UTC, tiltom commented on src/app/components/Form/AmountInput/index.tsx
> +  onChange: (value: string, isTotal?: boolean | undefined) => void;
You don't need to specify that `isTotal` can be either `boolean` or `undefined` since `?` already does that. So just remove `| undefined`.

2021-07-15 15:21 UTC, tiltom commented on src/app/components/Form/AmountInput/index.tsx
> +  onChange: (value: string, isTotal: boolean) => void;
Why `isTotal` is not optional here? I know you set `isTotal` later in `handleChange` but the function signature is exactly the same as in `Props`.

2021-07-15 15:21 UTC, tiltom commented on src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
> +    loading: rLoading,
Please rename to `rewardsLoading`, I don't like those abbreviations in the code.

2021-07-15 15:21 UTC, tiltom commented on src/app/pages/LendingPage/components/LendingDialog/index.tsx
> +    let wAmount = weiAmount;
Rename to `withdrawAmount` please.

2021-07-15 15:21 UTC, tiltom commented on src/app/pages/LendingPage/components/LendingDialog/index.tsx
> +              onChange={(value, isTotal) => {
Use `useCallback` here.

2021-07-16 09:42 UTC, soulBit approved these changes

2021-07-22 17:16 UTC, soulBit submitted a review, later dismissed

2021-07-23 08:16 UTC, JoeStorm99 approved these changes

2021-07-23 10:41 UTC, merged