Margin trading with slippage
DistributedCollective/Sovryn-frontend pull request #1559
Opened 2021-07-27 09:36 UTC by creed-victor

ABI changed, not backwards compatible so must be merged together with smart-contract updates on mainnet.

2021-08-09 11:52 UTC, boltsr reviewed
LGTM!

2021-08-13 10:22 UTC, soulBit submitted a review, later dismissed

2021-08-16 08:58 UTC, tiltom requested changes

2021-08-16 08:58 UTC, tiltom commented on src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
> +              onChange={e => setSlippage(e)}
```suggestion
              onChange={setSlippage}
```

2021-08-17 11:49 UTC, boltsr reviewed
LGTM!

2021-08-17 12:16 UTC, tiltom approved these changes

2021-08-18 09:46 UTC, soulBit approved these changes

2021-09-02 12:54 UTC, tiltom approved these changes

2021-09-03 13:00 UTC, merged