Feat/1494 replace moment
DistributedCollective/Sovryn-frontend pull request #1569
Opened 2021-07-27 15:55 UTC by ShynRou

Resolves #1494

Replaced moment with dayjs which is lighter, supports localized formatting and does not require a webpack hack for treeshaking.

2021-07-28 09:08 UTC, tiltom requested changes

2021-07-28 09:08 UTC, tiltom commented on src/app/components/StakingDateSelector/index.tsx
> +    const dateWithoutStake = filteredDates.reduce((unique: any, o: any) => {
I don't like this, use correct typing. `unique` is `DateItem[]` and `o` is `DateItem`. 

Also, adjust the naming - change `unique` to `uniqueDates` and `o` to `item` (or something else if you find it more suitable).

2021-07-28 11:10 UTC, tiltom submitted a review, later dismissed

2021-08-09 11:02 UTC, creed-victor approved these changes

2021-08-10 10:42 UTC, soulBit approved these changes
Removed `antd` package dependency as discussed

2021-08-10 10:42 UTC, merged