[browsers] update supported browsers and add a table to readme
DistributedCollective/Sovryn-frontend pull request #1601
Opened 2021-08-11 15:41 UTC by ShynRou

As discussed with @t-z-u, we only aim to support newish browser versions to not get bogged down by old or crappy browsers that have bad feature support. To represent that I updated the browserslist to support up to roughly 2 year old browser versions. 

Note: Brave is currently not supported by browserslist, but the chrome version mostly covers it.

2021-08-11 15:53 UTC, t-z-u commented
i only use brave!!!

2021-08-11 15:53 UTC, t-z-u requested changes
pls make brave work in the list

2021-08-11 17:43 UTC, ShynRou commented
@t-z-u as explained in discord, brave is supported by us just not by the tool "browserslist", that we use for automatically handling browser feature detection/handling. But since Brave is based on chromium and only differs in few features, we should be fine with having chrome in the list. 

https://github.com/browserslist/browserslist/issues/578
https://github.com/Fyrd/caniuse/issues/2749

2021-08-12 08:43 UTC, creed-victor approved these changes

2021-08-12 10:41 UTC, soulBit approved these changes

2021-08-13 06:35 UTC, merged