Feat/252 button
DistributedCollective/Sovryn-frontend pull request #1681
Opened 2021-09-02 14:07 UTC by ShynRou

Resolves https://taiga.sovryn.app/project/sovryn-light/task/263

2021-11-05 08:55 UTC, ShynRou commented
Still requires input from @t-z-u.

2022-03-15 12:20 UTC, soulBit requested changes
Reward page claim buttons text looks broken:
![image](https://user-images.githubusercontent.com/765825/158376172-ccb3b05c-a0ee-45ce-b57e-8e22546263f6.png)

same issue on FastBTC withdraw/deposit flow:
![image](https://user-images.githubusercontent.com/765825/158376216-132ca04d-11da-4d92-b809-9178570c782b.png)
![image](https://user-images.githubusercontent.com/765825/158376267-07be6c99-89b2-4a96-993c-f524c71ad2d3.png)

appears ok on first part of cross-chain flow, but I haven't gone through the entire flow to check every button instance:
![image](https://user-images.githubusercontent.com/765825/158376428-20438c8c-149a-4fbf-9323-322f51417d83.png)

2022-03-16 17:36 UTC, soulBit submitted a review, later dismissed

2022-03-27 12:56 UTC, soulBit approved these changes

2022-03-28 12:08 UTC, merged