Minor changes PT-BR
DistributedCollective/Sovryn-frontend pull request #1686
Opened 2021-09-03 17:37 UTC by bitcoinuser

2021-09-05 02:06 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +      "balance": "Meu saldo"
```suggestion
      "balance": "Saldo disponível"
```

2021-09-05 02:06 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +        "balance": "Meu saldo: <0/> <1/>",
```suggestion
        "balance": "Saldo disponível: <0/> <1/>",
```

2021-09-05 02:07 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +      "availableBalance": "Meu saldo:",
```suggestion
      "availableBalance": "Saldo disponível:",
```

2021-09-05 02:07 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "accountBalance": "Meu saldo",
```suggestion
    "accountBalance": "Saldo disponível",
```

2021-09-05 02:08 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "availableBalance": "Meu saldo:",
```suggestion
    "availableBalance": "Saldo disponível:",
```

2021-09-07 14:21 UTC, soulBit requested changes
@bitcoinuser can you remove the duplicate 'title' property from 'stakingForm' please
![image](https://user-images.githubusercontent.com/765825/132360977-3d907807-8d3d-4b97-af8e-599140694694.png)

2021-09-07 14:51 UTC, bitcoinuser commented
> @bitcoinuser can you remove the duplicate 'title' property from 'stakingForm' please
> ![image](https://user-images.githubusercontent.com/765825/132360977-3d907807-8d3d-4b97-af8e-599140694694.png)

Done. Can be merged now.

2021-09-07 15:05 UTC, merged