Feat/276 Table
DistributedCollective/Sovryn-frontend pull request #1691
Opened 2021-09-07 11:22 UTC by ShynRou

Resolves https://taiga.sovryn.app/project/sovryn-light/task/276

@t-z-u please review new table on /storybook.

2021-12-03 11:29 UTC, ShynRou commented
Still waiting on input from @t-z-u.

2022-03-14 10:42 UTC, tiltom requested changes

2022-03-14 10:42 UTC, tiltom commented on src/app/components/Table/index.tsx
> +  align?: 'left' | 'center' | 'right';
Create an enum for this (e.g. `CellAlignment`) and use it instead.

2022-03-14 10:42 UTC, tiltom commented on src/app/components/Table/index.tsx
> +type ITableProps<RowType extends RowObject> = {
```suggestion
type TableProps<RowType extends RowObject> = {
```

2022-03-14 10:42 UTC, tiltom commented on src/app/components/Table/index.tsx
> +  const onShowDetails = useCallback(row => showDetails && setOpenRow(row), [
Use `if`.

2022-03-14 10:42 UTC, tiltom commented on src/app/components/Table/index.tsx
> +type Breakpoint = 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | 'any';
Convert it to an enum pls.

2022-03-14 10:42 UTC, tiltom commented on src/app/components/Table/index.tsx
> +  index: number;
Unused.

2022-03-27 15:08 UTC, soulBit requested changes
See requested changes that import row styling for cases when no data is present

2022-03-27 15:08 UTC, soulBit commented on src/app/components/Table/index.tsx
> +import styles from './index.module.scss';
```suggestion
import styles from './index.module.scss';
import rowStyles from './components/TableRow/index.module.scss';
```

2022-03-27 15:08 UTC, soulBit commented on src/app/components/Table/index.tsx
> +              <tr className={styles.row}>
```suggestion
              <tr className={rowStyles.row}>
```

2022-03-28 12:27 UTC, merged