Fix/remove text stroke
DistributedCollective/Sovryn-frontend pull request #1739
Opened 2021-09-16 10:24 UTC by ShynRou

Removed the text-stroke property as discussed with @t-z-u.

Requires @t-z-u's review and approval.

2022-03-14 11:12 UTC, ShynRou commented
Has been approved by gilad.
https://sovryn.monday.com/boards/2218344956/pulses/2236542194/posts/1342661151

2022-03-14 13:28 UTC, tiltom submitted a review, later dismissed

2022-03-14 17:49 UTC, soulBit requested changes
Changes look good, but I spotted a few instances still using `font-weight: 100` in the dapp:

Lend page
![image](https://user-images.githubusercontent.com/765825/158168518-47ff188f-83e7-4477-bcfd-232a811929cc.png)

Yield Farm page
![image](https://user-images.githubusercontent.com/765825/158231031-81562815-ebb0-4c57-968e-c562afd9fc2b.png)

2022-03-15 11:43 UTC, soulBit approved these changes

2022-03-22 18:47 UTC, merged