Perpetual swaps
DistributedCollective/Sovryn-frontend pull request #1779
Opened 2021-10-01 08:06 UTC by tiltom

2022-03-01 13:35 UTC, creed-victor requested changes

2022-03-01 13:35 UTC, creed-victor commented on src/app/pages/PerpetualPage/components/RecentTradesTable/types.ts
> +}
```suggestion
export enum TradePriceChange {
  UP = 'up',
  DOWN = 'down',
  NO_CHANGE = 'noChange',
}

export enum TradeType {
  SELL = 'sell',
  BUY = 'buy',
}
```

2022-03-08 09:40 UTC, ShynRou commented on src/app/components/HeaderLabs/index.module.scss
> +  }
good catch

2022-03-25 12:15 UTC, soulBit requested changes

2022-03-29 15:56 UTC, ShynRou commented on src/app/hooks/useSendContractTx.ts
>  export interface TransactionOptions {
Yeah we should make a definitive decision on that, we have 213 instances of interfaces that don't start with I :sweat_smile:
We should probably handle it all in one swoop.

2022-03-29 15:56 UTC, ShynRou commented on src/app/hooks/useSendContractTx.ts
>  export interface TransactionOptions {
Will not change it here for now.

2022-03-29 15:58 UTC, ShynRou commented on src/app/pages/MarginTradePage/components/AdvancedSettingDialog/index.tsx
> +// import { discordInvite } from 'utils/classifiers';
Ah shit. We totally forgot about this stuff. I'll need to revert all the margin page changes to the development state.

2022-03-29 18:50 UTC, ShynRou commented on src/app/pages/MarginTradePage/components/AdvancedSettingDialog/index.tsx
> +// import { discordInvite } from 'utils/classifiers';
Fixed it reverted the whole MarginTradePage to development.

2022-04-05 12:34 UTC, creed-victor submitted a review, later dismissed

2022-04-11 11:52 UTC, creed-victor approved these changes

2022-04-12 12:56 UTC, creed-victor submitted a review, later dismissed

2022-04-12 16:42 UTC, creed-victor approved these changes

2022-04-14 14:08 UTC, tiltom commented
Merged in https://github.com/DistributedCollective/Sovryn-frontend/pull/2136

2022-04-14 14:08 UTC, closed without merging