Feat/tenderly estimator
DistributedCollective/Sovryn-frontend pull request #1781
Opened 2021-10-01 14:07 UTC by creed-victor

2021-11-02 12:39 UTC, tiltom requested changes

2021-11-02 12:39 UTC, tiltom commented on src/app/hooks/simulator/useFilterSimulatorResponseLogs.ts
> +  return useMemo(() => {
You don't need to use `useMemo` here.

2021-11-03 09:26 UTC, tiltom approved these changes

2021-11-03 12:19 UTC, soulBit approved these changes

2021-11-05 12:33 UTC, merged