Feat/trade review modal
DistributedCollective/Sovryn-frontend pull request #1847
Opened 2021-11-01 09:26 UTC by rick23p

2021-11-02 14:01 UTC, ShynRou requested changes

2021-11-03 09:00 UTC, tiltom requested changes

2021-11-03 09:00 UTC, tiltom commented on src/app/pages/MarginTradePage/components/TxFeeCalculator/TransactionFee.tsx
> +TransactionFee.defaultProps = {
Don't use `defaultProps`, destructure them in the function header as Shyn suggested.

2021-11-11 10:20 UTC, tiltom requested changes

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/dialog.module.scss
> +  width: 42px;
You have some properties (`border`, `position`) here that have standard tailwind values so you could use `@apply tw-...`.

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/dialog.module.scss
> +  opacity: 0.8;
```suggestion
  @apply tw-opacity-80
```

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/dialog.module.scss
> +  max-width: 80rem;
You don't need this selector because `max-width: 80rem` is a standard tailwind value (`max-w-7xl`) and you can apply it directly to the element.

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/dialog.module.scss
> +  width: 160px;
You don't need this selector as those are standard tailwind values, apply classes directly to the element.

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/dialog.module.scss
> +  width: 85px;
Use `@apply` where you can.

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/dialog.module.scss
> +  width: 4rem;
I think you don't need this selector as well.

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/index.tsx
> +  const close = useCallback(() => tx.reset(), [tx]);
```suggestion
  const onClose = useCallback(() => tx.reset(), [tx]);
```

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/index.tsx
> +export const WalletLogo: React.FC<WalletLogoProps> = ({ wallet }) => (
This could be a separate component.

2021-11-11 10:20 UTC, tiltom commented on src/app/components/TransactionDialog/index.tsx
> +const getWalletName = wallet => {
All of those helper methods could be extract to a separate file (e.g. `utils.ts`) because I think this component is huge for no reason.

2021-11-11 10:20 UTC, tiltom commented on src/app/containers/WalletProvider/components/TxRequestDialog.tsx
> +                    'tw-flex tw-items-center tw-justify-center tw-h-12 tw-rounded-lg tw-w-80 tw-mx-auto'
```suggestion
                  className="tw-flex tw-items-center tw-justify-center tw-h-12 tw-rounded-lg tw-w-80 tw-mx-auto"
```

2021-11-11 10:20 UTC, tiltom commented on src/app/containers/WalletProvider/components/TxRequestDialog.tsx
>  `;
We don't use styled components anymore and I saw the same styles in `TransactionDialog`. Adjust it the same way.

2021-11-11 10:20 UTC, tiltom commented on src/app/pages/MarginTradePage/components/TxFeeCalculator/TransactionFee.tsx
> +            (gas limit: {gasLimit} units)
Use localized strings.

2021-11-11 10:20 UTC, tiltom commented on src/app/pages/MarginTradePage/components/TxFeeCalculator/TransactionFee.tsx
> +            (gas price: {toNumberFormat(Number(fromWei(gasPrice, 'gwei')), 3)}{' '}
Use localized strings.

2021-11-11 10:20 UTC, tiltom commented on src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
> +        onUserConfirmed={() => {}}
```suggestion
        onUserConfirmed={noop}
```

2021-11-11 10:20 UTC, tiltom commented on src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
> +          <div className="tw-text-center tw-w-full">Spot Trade</div>
Use localized strings.

2021-11-18 12:17 UTC, tiltom requested changes

2021-11-18 12:17 UTC, tiltom commented on src/app/components/TransactionDialog/index.tsx
> +          i18nKey={'translations.transactionDialog.pendingUser.failed'}
Does this work? Because this is the first time I see `i18nKey` passed as a string and I don't think it should work.

2021-11-18 12:17 UTC, tiltom commented on src/app/components/TransactionDialog/utils.ts
> +export const getStatusImage = (tx: TxStatus) => {
Rewrite to a `switch` statement as well.

2021-11-18 13:13 UTC, closed without merging