add new Transaction reveiw dialog.
DistributedCollective/Sovryn-frontend pull request #1889
Opened 2021-11-18 13:16 UTC by rick23p

2021-11-18 13:21 UTC, tiltom requested changes

2021-11-18 13:21 UTC, tiltom commented on src/app/components/TransactionDialog/TxRequestDialog.tsx
> +interface Props extends RequestDialogState {}
No need to do that, just use `RequestDialogState` as your props.

2021-11-18 13:21 UTC, tiltom commented on src/app/components/TransactionDialog/index.tsx
> +import cn from 'classnames';
```suggestion
import classNames from 'classnames';
```

2021-12-15 10:55 UTC, ShynRou commented
Sorry for the inconvenience @rick23p, sadly we cannot use your code for perpetuals.

2021-12-15 10:55 UTC, closed without merging