Feat/perpetuals recent trades
DistributedCollective/Sovryn-frontend pull request #1907
Opened 2021-11-26 12:24 UTC by BetsyBraddock

Added a ContextProvider for getting recent trades. The provider is in this file: https://github.com/DistributedCollective/Sovryn-frontend/blob/feat/perpetuals-recent-trades/src/app/pages/PerpetualPage/components/RecentTradesTable/context.tsx

It loads the first 50 most recent trades, and then connects to the bsc websocket to live stream trades.

It is being consumed here: https://github.com/DistributedCollective/Sovryn-frontend/blob/feat/perpetuals-recent-trades/src/app/pages/PerpetualPage/components/RecentTradesTable/index.tsx#L17

I have not yet changed the candlestick chart to use the context provider, but that is the purpose of the fromSocket property - the candlestick chart should only add the trades from the websocket.

2021-11-29 09:09 UTC, ShynRou requested changes
You do not need to use the context for the candles.

Please fix the multiple listener problem.

2021-11-29 09:09 UTC, ShynRou commented on src/app/pages/PerpetualPage/utils/bscWebsocket.ts
> +
```suggestion
```

2021-11-30 13:22 UTC, tiltom requested changes

2021-11-30 13:22 UTC, tiltom commented on src/app/pages/PerpetualPage/components/RecentTradesTable/context.tsx
> +      time: new Date(parseInt(trade.blockTimestamp) * 1e3)
Extract to a local function (e.g. `convertTimestampToTime`) and use the function (on both places in this file).

2021-11-30 13:22 UTC, tiltom commented on src/app/pages/PerpetualPage/components/RecentTradesTable/context.tsx
> +      type: trade.tradeAmount[0] === '-' ? TradeType.SELL : TradeType.BUY,
Extract to a local function (e.g. `getTradeType`) and use the function (on both places in this file).

2021-11-30 13:22 UTC, tiltom commented on src/app/pages/PerpetualPage/components/RecentTradesTable/context.tsx
> +  const { data, error, loading } = useGetRecentTrades(
`loading` is unused

2021-12-01 09:40 UTC, ShynRou requested changes

2021-12-01 09:40 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/RecentTradesTable/context.tsx
> +    };
This does not solve the original issue of potentially infinitely adding listeners and will create a new one, since the subscription is never renewed.

2021-12-01 15:10 UTC, tiltom approved these changes

2021-12-01 15:36 UTC, merged