Feat/525 Perpetual Trade Process
DistributedCollective/Sovryn-frontend pull request #1917
Opened 2021-12-02 18:17 UTC by ShynRou

Resolves https://taiga.sovryn.app/project/sovryn-light/task/525

2021-12-03 12:00 UTC, tiltom requested changes

2021-12-03 12:29 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
> +          ? new Error('Transaction failed for an unknown reason!')
With the default useSendContractTx we don't get an error message for rejected or underpriced transactions. We could just always count them as rejeted and show no error message.

2021-12-03 12:31 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
> +      reset();
Completely forgot this existed :D

2021-12-03 12:41 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
> +      transactions[0]?.method === PerpetualTxMethods.deposit
As discussed will leave it for now. Also found a minor issue in checkAndApprove where it requests approval when the exact amount already had been approved.

2021-12-03 12:44 UTC, tiltom commented on src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
> +          ? new Error('Transaction failed for an unknown reason!')
If we cannot display the exact reason or something more helpful, I wouldn't show the message because this adds no additional info to our users.

2021-12-03 13:10 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
> +          ? new Error('Transaction failed for an unknown reason!')
Okey I'll switch it to default to rejected then.

2021-12-03 14:37 UTC, tiltom requested changes

2021-12-03 14:37 UTC, tiltom commented on src/app/components/UserAssets/TxDialog/dialog.module.scss
> +    tw-overflow-hidden;
```suggestion
  @apply tw-flex tw-flex-col tw-justify-between tw-items-center 
    tw-w-40 tw-h-40 tw-mx-auto
    tw-border-sov-white tw-rounded-3xl
    tw-overflow-hidden tw-border-solid;
```

2021-12-03 14:37 UTC, tiltom commented on src/app/components/UserAssets/TxDialog/dialog.module.scss
> +  border-style: solid;
```suggestion

```

2021-12-08 07:59 UTC, tiltom requested changes

2021-12-08 07:59 UTC, tiltom commented on src/app/pages/PerpetualPage/components/SlippageForm/index.tsx
> +const SLIPPAGE_MAX = process.env.REACT_APP_NETWORK === 'mainnet' ? 0.01 : 0.02;
I see we use this condition on 2 other places in the dapp, extract it to a global constant.

2021-12-08 07:59 UTC, tiltom commented on src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
> +  const [lotSize, lotPrecision] = useMemo(() => {
We use this in 2 other places, either extract it to a util function or add it to `PerpetualQueriesContext`.

2021-12-08 09:43 UTC, merged