Fix Team SOV vesting history
DistributedCollective/Sovryn-frontend pull request #1978
Opened 2021-12-30 09:19 UTC by tiltom

2021-12-30 09:36 UTC, ShynRou requested changes

2021-12-30 09:36 UTC, ShynRou commented on src/app/hooks/staking/useVesting_getTeamVesting.ts
> +    62899200, // 24 months in seconds
```suggestion
    62899200, // 26 * 28 day cycles  (~24 months)  in seconds
```

2021-12-30 09:36 UTC, ShynRou commented on src/app/hooks/staking/useVesting_getTeamVesting.ts
> +    1,
Could you add a comment explaining why 1 is used here.

2021-12-30 09:46 UTC, ShynRou submitted a review, later dismissed

2021-12-30 10:55 UTC, grinry approved these changes

2022-01-10 10:07 UTC, creed-victor submitted a review, later dismissed

2022-01-12 11:25 UTC, JoeStorm99 approved these changes

2022-01-12 11:28 UTC, merged