Feat/lending data attr
DistributedCollective/Sovryn-frontend pull request #1985
Opened 2022-01-12 10:25 UTC by rick23p

2022-01-14 11:27 UTC, soulBit requested changes
Few small changes to make based on some errors in the spec

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/BorrowPage/BorrowingContainer/index.tsx
> +                  dataActionId="borrow-assetToCollatelizeAmountDropDown"
```suggestion
                  dataActionId="borrow-assetToCollateralizeAmountDropDown"
```

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
> +            data-action-id={`lend-deposit-button-${asset}`}
```suggestion
            data-action-id={`lend-depositButton-${asset}`}
```
This was defined incorrectly on the spec

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
> +            data-action-id={`lend-withdrawal-button-${asset}`}
```suggestion
            data-action-id={`lend-withdrawalButton-${asset}`}
```
This was defined incorrectly on the spec

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
> +              data-action-id="yieldFarm-deposit-button"
```suggestion
              data-action-id="yieldFarm-liquidityModal-confirm"
```

Spec has been updated to use a shared attribute name for the confirm buttons on both add/remove liquidity modals

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
> +              data-action-id="yieldFarm-deposit-button"
```suggestion
              data-action-id="yieldFarm-liquidityModal-confirm"
```
Spec has been updated to use a shared attribute name for the confirm buttons on both add/remove liquidity modals

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LiquidityMining/components/MiningPool/index.tsx
> +          data-action-id={`yieldFarm-deposit-button-${pool.key}`}
```suggestion
          data-action-id={`yieldFarm-depositButton-${pool.key}`}
```

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LiquidityMining/components/MiningPool/index.tsx
> +          data-action-id={`yieldFarm-withdrawal-button-${pool.key}`}
```suggestion
          data-action-id={`yieldFarm-withdrawalButton-${pool.key}`}
```

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
> +              data-action-id="yieldFarm-withdrawal-button"
```suggestion
              data-action-id="yieldFarm-liquidityModal-confirm"
```

Spec has been updated to use a shared attribute name for the confirm buttons on both add/remove liquidity modals

2022-01-14 11:27 UTC, soulBit commented on src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
> +              data-action-id="yieldFarm-withdrawal-button"
```suggestion
              data-action-id="yieldFarm-liquidityModal-confirm"
```

Spec has been updated to use a shared attribute name for the confirm buttons on both add/remove liquidity modals

2022-01-14 14:26 UTC, tiltom requested changes
The code itself looks ok but I was inspecting screens and the Borrow page (https://taiga.sovryn.app/project/sovryn-light/task/698) is not done according to the spec - I was only able to find `borrow-amountInput` attribute, all the others are missing.

2022-01-17 15:28 UTC, tiltom approved these changes

2022-01-26 10:57 UTC, soulBit approved these changes

2022-01-26 11:02 UTC, JoeStorm99 approved these changes

2022-01-26 11:03 UTC, merged