Feat/678 Perpetual Meta Transactions
DistributedCollective/Sovryn-frontend pull request #2010
Opened 2022-01-21 14:33 UTC by ShynRou

Resolves https://taiga.sovryn.app/project/sovryn-light/task/678

Transactions are failing at the moment when using GSN: I suspect an issue on the contract side.
Due to this Meta Transactions are likely not to be used for the competition. :sob: 

Optional: Add some localStorage saving and loading

2022-02-09 15:34 UTC, ShynRou commented
The buttons on the Perpetuals Account modal will be changed to "BTC Deposit", "BTC Withdraw", "RSK Transfer" respectively. Tooltips may be asked for as well (waiting on decision of vasili)

2022-02-10 13:39 UTC, tiltom requested changes

2022-02-10 16:19 UTC, ShynRou commented on src/app/hooks/useGsnSendTx.ts
> +            typeof result === 'string' ? result : result?.transactionHash;
typeof checks are basic syntax and I don't think a isString function would really add anything

2022-02-11 08:51 UTC, tiltom approved these changes

2022-02-11 09:43 UTC, merged