Fix leverage selector and max trade size
DistributedCollective/Sovryn-frontend pull request #2014
Opened 2022-01-25 10:01 UTC by tiltom

2022-01-26 07:42 UTC, creed-victor approved these changes

2022-02-01 16:57 UTC, ShynRou approved these changes

2022-02-01 16:57 UTC, ShynRou commented on src/locales/en/translation.json
> -      },
Should not be removed on the perpetual main branch

2022-02-01 16:58 UTC, ShynRou requested changes
Please remove the noted changes

2022-02-02 10:07 UTC, tiltom commented on src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
> -    <div className="tw-flex-grow tw-p-4 tw-text-xs">
Yes, you're right, I forgot it here :)

2022-02-02 14:31 UTC, ShynRou approved these changes

2022-02-02 14:32 UTC, merged