Feat/withdraw multiple assets
DistributedCollective/Sovryn-frontend pull request #2015
Opened 2022-01-26 11:10 UTC by rick23p

https://sovryn.monday.com/boards/2135418157/pulses/2135555847

2022-01-26 15:32 UTC, tiltom requested changes

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +  contract: string;
Again, this is not a contract but a contract address. Rename it to either `contractAddress` or `assetContractAddress`.

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +export const useGetFeesEarned = () => {
This is just a local function, no need to `export` it.

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +        const rate = item ? fixNumber(item.value.rate) : '0';
```suggestion

```

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +        );
```suggestion
        const rate = fixNumber(assetRates.find(
          item => item.source === fee.asset && item.target === Asset.RBTC,
        ));
```

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +        );
`fixNumber` method is dealing with edge cases and in case that rate is `undefined`, it will return `0`. No need for line `31`.

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +const fees = [
```suggestion
const defaultEarnedFees = [
```

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +type IAccumulatedFeesData = {
```suggestion
type AccumulatedFeesData = {
```

2022-01-26 15:32 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedEvents.ts
> +                .toFixed(0);
The same calculation as in `useGetFeesEarnedClaimAmount.ts`. Extract it to a function (e.g. `calculateAssetRbtcValue`) that will accept 2 parameters - `AssetDetails` and `amount`.

2022-01-27 12:19 UTC, soulBit requested changes
Can you add the "approximately equals to" symbol to the locations marked in red on my screenshot:
![image](https://user-images.githubusercontent.com/765825/151357627-05820830-3a0a-43cd-adbf-385266234d93.png)

2022-01-28 09:43 UTC, tiltom requested changes

2022-01-28 09:43 UTC, tiltom commented on src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
> +export const FeeValue: React.FC<IFeeValueProps> = ({ value, asset }) => (
```suggestion
 const FeeValue: React.FC<IFeeValueProps> = ({ value, asset }) => (
```

2022-01-28 09:43 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +const defaultEarnedFees = [
```suggestion
const defaultEarnedFees: IEarnedFee[] = [
```

2022-01-28 09:43 UTC, tiltom commented on src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
> +  const [earnedFees, setEarnedFees] = useState<IEarnedFee[]>(defaultEarnedFees);
```suggestion
  const [earnedFees, setEarnedFees] = useState(defaultEarnedFees);
```

2022-01-28 09:43 UTC, tiltom commented on src/utils/helpers.ts
> +  return numberFromWei(bignumber(amount).mul(rate));
Don't you need to divide it by the asset's number of decimals?

2022-01-28 12:57 UTC, tiltom commented on src/utils/helpers.ts
> +  return numberFromWei(bignumber(amount).mul(rate));
My bad, `numberFromWei` does that.

2022-01-28 13:54 UTC, tiltom approved these changes

2022-02-02 12:06 UTC, creed-victor approved these changes

2022-02-02 17:22 UTC, soulBit approved these changes
Tested MYNT and SOV withdrawals, both worked well - Tyrone has deposited MYNT token into feeSharingProxy so this should be testable by anyone with staked SOV on testnet

2022-02-03 15:43 UTC, JoeStorm99 approved these changes

2022-02-04 11:24 UTC, merged