Header cleanup
DistributedCollective/Sovryn-frontend pull request #2052
Opened 2022-02-15 12:47 UTC by tiltom

Resolves https://sovryn.monday.com/boards/2218344956/pulses/2279395587

2022-02-16 09:54 UTC, ShynRou requested changes

2022-02-16 09:54 UTC, ShynRou commented on src/app/components/Header/index.tsx
> +                'tw-btn-action tw-hidden sm:tw-flex tw-mr-2 xl:tw-mr-4',
Add margin on the left, switch to mr-4 a breakpoint later. to cleanup issues around 1200px 
```suggestion
                'tw-btn-action tw-hidden sm:tw-flex tw-mx-2 2xl:tw-mr-4',
```

2022-02-17 12:21 UTC, creed-victor submitted a review, later dismissed

2022-02-18 11:20 UTC, ShynRou approved these changes

2022-02-18 13:17 UTC, creed-victor approved these changes

2022-02-20 02:14 UTC, soulBit approved these changes

2022-02-21 08:22 UTC, merged

2022-02-21 12:13 UTC, JoeStorm99 commented
C. fails te Deposit disapears when on mobile view. 
<img width="493" alt="Screenshot 2022-02-21 at 12 09 30" src="https://user-images.githubusercontent.com/85491205/154953081-12f2a6bb-e9ce-4f75-a48a-e6dd824a5248.png">

B. The SOVRYN ALPHA logo is meant to be possionted to the middle but this is not so see screenshot for more information

<img width="1137" alt="Screenshot 2022-02-21 at 12 09 44" src="https://user-images.githubusercontent.com/85491205/154953254-3faaf9b6-bd5f-45f4-94e4-b5b1df53b541.png">

2022-02-21 12:19 UTC, tiltom commented
> C. fails te Deposit disapears when on mobile view. <img alt="Screenshot 2022-02-21 at 12 09 30" width="493" src="https://user-images.githubusercontent.com/85491205/154953081-12f2a6bb-e9ce-4f75-a48a-e6dd824a5248.png">
> 
> B. The SOVRYN ALPHA logo is meant to be possionted to the middle but this is not so see screenshot for more information
> 
> <img alt="Screenshot 2022-02-21 at 12 09 44" width="1137" src="https://user-images.githubusercontent.com/85491205/154953254-3faaf9b6-bd5f-45f4-94e4-b5b1df53b541.png">

Have you read the specification Jonathan? Because both of the reported issues were part of this task and this is the wanted behaviour.