fix(staking): page inconsistencies
DistributedCollective/Sovryn-frontend pull request #2072
Opened 2022-02-24 12:37 UTC by creed-victor

https://sovryn.monday.com/boards/2218344956/pulses/2273556093

2022-02-25 12:55 UTC, ShynRou commented
Looks pretty good, but there is still a state where the vests table is displayed as empty, it should either show a loading text or the you have not vests text.
![image](https://user-images.githubusercontent.com/20092263/155718635-0a147e19-9ed6-4595-8d09-ae5acf618b77.png)

2022-02-25 13:11 UTC, tiltom approved these changes

2022-02-25 17:08 UTC, ShynRou requested changes
See comment above

2022-03-01 11:57 UTC, JoeStorm99 approved these changes

2022-03-09 07:47 UTC, tiltom requested changes

2022-03-09 07:47 UTC, tiltom commented on src/app/containers/StakePage/components/VestingContract.tsx
> +          <p className={`tw-m-0 ${lockedAmount.loading && 'tw-skeleton'}`}>
```suggestion
          <p className={classNames('tw-m-0', {
          'tw-skeleton': lockedAmount.loading }
          )}>
```

2022-03-09 07:47 UTC, tiltom commented on src/app/containers/StakePage/components/VestingContract.tsx
> +          <p className={`tw-m-0 ${delegateLoading && 'tw-skeleton'}`}>
```suggestion
          <p className={classNames('tw-m-0', {
           'tw-skeleton': delegateLoading}
           )}>
```

2022-03-09 07:47 UTC, tiltom commented on src/app/containers/StakePage/components/VestingContract.tsx
> +                  }`}
```suggestion
                  className={classNames('tw-text-secondary hover:tw-underline'), {
                    'tw-skeleton': delegateLoading
                  }) }
```

2022-03-09 07:47 UTC, tiltom commented on src/app/containers/StakePage/components/VestingContract.tsx
> +            <p className={`tw-m-0 ${!unlockDate && 'tw-skeleton'}`}>
```suggestion
            <p className={classNames('tw-m-0', {
            'tw-skeleton': !unlockDate}
            )}>
```

2022-03-09 07:47 UTC, tiltom commented on src/app/containers/StakePage/components/VestingContract.tsx
> +          <p className={`tw-m-0 ${!stakingPeriodStart && 'tw-skeleton'}`}>
```suggestion
          <p className={classNames('tw-m-0', {
          'tw-skeleton': !stakingPeriodStart}
          )}>
```

2022-03-14 13:00 UTC, tiltom submitted a review, later dismissed

2022-03-15 08:49 UTC, ShynRou submitted a review, later dismissed

2022-03-16 11:48 UTC, soulBit approved these changes

2022-03-16 12:13 UTC, JoeStorm99 approved these changes

2022-03-17 13:07 UTC, soulBit requested changes
Re-reviewed this and noticed that withdraw buttons are missing for some assets in the Fee Claiming block (tested this on mainnet):

![image](https://user-images.githubusercontent.com/765825/158812577-a3920c8c-1210-4f49-9254-09c3ada87717.png)

2022-04-06 12:34 UTC, creed-victor commented
> Re-reviewed this and noticed that withdraw buttons are missing for some assets in the Fee Claiming block (tested this on mainnet)

Amount to withdraw is 0, do you prefer on still being able to see the button?

2022-04-08 10:23 UTC, JoeStorm99 submitted a review, later dismissed

2022-04-13 10:46 UTC, soulBit approved these changes

2022-04-13 10:46 UTC, merged