Perpetual layout menu
DistributedCollective/Sovryn-frontend pull request #2086
Opened 2022-03-07 12:55 UTC by tiltom

2022-03-09 18:22 UTC, ShynRou commented
![image](https://user-images.githubusercontent.com/20092263/157505739-41d877ad-0286-4bf9-8621-f0527216b444.png)
I changed a few things from the original design and the previous version:
1. The GSN stays on the right side as, left aligning it on the customize layout button makes no sense
2.  I didn't implement the merged dropdown, as it would need to be new custom component and I don't see the value in that atm. Could be something we should add to the Atomic Components Backlog.
3. I stretched the DataCard components vertically to fill the screen size, except for the Place New Order Card as this one requires a set height.

2022-03-11 16:59 UTC, soulBit requested changes
Code and functionality seems ok, but please clean up the build warnings before merging:
![image](https://user-images.githubusercontent.com/765825/157912702-ef96e382-bdd0-43d2-8d4b-ade71d4835af.png)

2022-03-14 11:07 UTC, tiltom reviewed
I cannot request changes on my PRs so I submit these as comments :D

2022-03-14 11:07 UTC, tiltom commented on src/app/pages/PerpetualPage/components/LayoutMenu/index.tsx
> +type LayoutMenuProps = {};
Unnecessary, delete it pls.

2022-03-14 11:07 UTC, tiltom commented on src/app/pages/PerpetualPage/components/LayoutMenu/index.tsx
> +          className={'tw-w-3 tw-ml-2'}
```suggestion
          className="tw-w-3 tw-ml-2"
```

2022-03-14 13:48 UTC, ShynRou commented
Fixed issues raised by @tiltom and removed dead variable `connected` @soulBit.
Critical dependency error is in a function that we do not use in the fronend tudor should fix that in the package.
transferAccountLocked should by addressed in #2071.

2022-03-14 15:57 UTC, tiltom reviewed
I cannot approve the request so take this as my approval :D

2022-03-16 13:02 UTC, soulBit approved these changes

2022-03-16 13:02 UTC, merged