Feat/2236012071 tabs atomic component
DistributedCollective/Sovryn-frontend pull request #2088
Opened 2022-03-08 09:27 UTC by rick23p

https://sovryn.monday.com/boards/2218344956/pulses/2236012071

2022-03-09 10:14 UTC, tiltom requested changes

2022-03-09 10:14 UTC, tiltom commented on src/app/components/Tabs/index.tsx
> +    setActiveTab(item.id);
```suggestion
    if (item.disabled) {
      return;
    }
    setActiveTab(item.id);
```

2022-03-09 10:14 UTC, tiltom commented on src/app/components/Tabs/index.tsx
> +  const selectTab = (item: ITabItem) => {
Use `useCallback`.

2022-03-10 07:50 UTC, tiltom submitted a review, later dismissed

2022-03-10 21:32 UTC, pietro-maximoff commented
just a quick suggestion here, maybe make sense to add an option that will allow you to combine all tabs into one select element based on media breakpoints, its more useful for mobile devices.
for instance if we have 3 or more tabs then we can hide them on mobile and show one select element, that's will be more conveniently.
<img width="441" alt="Screenshot at Mar 10 23-22-01" src="https://user-images.githubusercontent.com/74987028/157757755-491fef15-6907-48d8-8be8-7202f340c481.png">

2022-03-11 11:47 UTC, JoeStorm99 approved these changes

2022-03-17 11:18 UTC, ShynRou commented
@pietro-maximoff That's a good point, but I think that should be something we address at a later stage.

2022-03-17 11:42 UTC, ShynRou requested changes

2022-03-17 11:42 UTC, ShynRou commented on src/app/components/Tab/index.tsx
> +        'tw-opacity-50': disabled,
```suggestion
        'tw-opacity-50 tw-cursor-not-allowed': disabled,
```

2022-03-17 11:42 UTC, ShynRou commented on src/app/components/Tabs/index.tsx
> +            className="tw-mr-2"
```suggestion
            className="tw-mx-2"
```

2022-03-17 11:42 UTC, ShynRou commented on src/app/components/Tab/index.tsx
> +  <span
Can you please make this into a button, so it is focus-able and shows up on screen readers.

2022-03-27 19:27 UTC, soulBit submitted a review, later dismissed
Reviewed code and resolved previous comments

2022-03-28 12:50 UTC, merged