add switch atomic component
DistributedCollective/Sovryn-frontend pull request #2097
Opened 2022-03-15 09:30 UTC by pietro-maximoff

2022-03-15 11:41 UTC, soulBit approved these changes

2022-03-15 12:24 UTC, rick23p commented
If ```innerLabelChecked``` is empty and ```innerLabel``` has value (or vice versa ) then on toggle the checkbox jumps up and down

2022-03-15 12:27 UTC, rick23p commented
Tested on Safari: (not aligned)
<img width="362" alt="Screen Shot 2022-03-15 at 3 57 15 PM" src="https://user-images.githubusercontent.com/81699526/158377526-273db6e2-04ef-4715-ba5d-4ce051a04d84.png">

2022-03-15 12:30 UTC, rick23p commented
I think giving it a "tw-select-none" might be good to avoid the text being selected on clicks
<img width="362" alt="Screen Shot 2022-03-15 at 3 59 24 PM" src="https://user-images.githubusercontent.com/81699526/158377845-be846e2e-2ee6-4d54-8289-fae2dee6b55f.png">

2022-03-15 12:33 UTC, rick23p requested changes

2022-03-15 12:33 UTC, rick23p commented on src/app/components/Switch/index.tsx
> +          { 'tw-cursor-not-allowed tw-opacity-30': disabled },
let's use "tw-opacity-50" to be more consistent with other atomic components

2022-03-15 13:16 UTC, JoeStorm99 commented
The Switch is not properly aligned on Safari 

<img width="640" alt="Screenshot 2022-03-15 at 13 15 21" src="https://user-images.githubusercontent.com/85491205/158385837-0e61be79-e6f8-482b-8090-e279c437272c.png">

2022-03-15 13:18 UTC, JoeStorm99 requested changes
please read the comments below, the switch is not properly aligned on Safari. 
I have also attached a screenshot.

2022-03-15 13:55 UTC, rick23p approved these changes

2022-03-15 18:02 UTC, soulBit submitted a review, later dismissed

2022-03-16 10:55 UTC, JoeStorm99 commented
Well-aligned on safari and all working well 
<img width="1355" alt="Screenshot 2022-03-16 at 10 51 46" src="https://user-images.githubusercontent.com/85491205/158574496-56e73c5a-36ce-4d88-bf38-4bc43ff3c84c.png">

2022-03-16 11:45 UTC, JoeStorm99 approved these changes
now working as expected on all browsers including Safari

2022-03-16 11:52 UTC, Alitasovryn approved these changes

2022-03-16 11:56 UTC, merged

2022-03-17 12:20 UTC, ShynRou commented
This component will need to be updated again, the component currently completely ignores the existing switch design. The inner labels also don't work particularly well. I'm sorry the spec may not have made it clear enough that it should match the currently implemented design. (CSS override for the blueprint version).

2022-03-17 12:21 UTC, ShynRou commented
I will do the once over as a new PR.