universal header component (part 1)
DistributedCollective/Sovryn-frontend pull request #2098
Opened 2022-03-15 13:42 UTC by creed-victor

A page container component which wraps router and has power to enable/disable header and footer, also swap default header or footer components from within page.
Leaving page where options were customised will reset settings back to defaults.

Usage (if needed to change header, footer or pass props to header from within page):

```tsx
const SomeCustomPage = () => {
   const page = usePageActions();
   useLayoutEffect(() => {
      // all options are optional
      page.setOptions({
         header: HeaderType.CROSS_CHAIN,
         footer: FooterTypes.NONE,
         headerProps: { address: receiver },
      });
   }, [page]);
  return (
     <span>Hello</span>
  );
};
```

part 2 will be PR to perpetuals with header for Labs.

2022-03-15 16:38 UTC, JoeStorm99 commented
The following pages have a different header, however, I am aware of FastBTC should have a different header this is clearly stated on the PR but the Governance and 


<img width="1233" alt="Screenshot 2022-03-15 at 16 34 58" src="https://user-images.githubusercontent.com/85491205/158427488-c9e22729-a654-4f42-b2ad-8b4c3759b0b8.png">
the Forum page and the Help has a different header: 


<img width="1263" alt="Screenshot 2022-03-15 at 16 32 06" src="https://user-images.githubusercontent.com/85491205/158427513-2f6697ac-db1d-4a53-8232-6eedefbd864a.png">

<img width="1384" alt="Screenshot 2022-03-15 at 16 25 59" src="https://user-images.githubusercontent.com/85491205/158427531-99a90b8a-c8e3-4e93-81ce-1147564b70eb.png">

2022-03-15 16:59 UTC, ShynRou requested changes
I'm sorry, but I don't think your solution to use redux for it is any good.
1. Functions/Components should never be passed into the redux store.
2. Each header change will need to be called by the component that requests the change, this means that a) all pages need to call the set function and b) the async nature of the pages will result in the header change only happening after the new page has been loaded.

I would suggest using the react-router for it, which eliminates all issues with handling the page changes. If you want to have the configuration in the page files instead of one centralized place you could add a register function, that is called statically outside of the page components.

2022-03-15 17:02 UTC, ShynRou commented
@JoeStorm99 None of the pages listed by you are part of this repository and with that out of the scope of this task.

2022-03-17 11:14 UTC, ShynRou requested changes
Looks already better and I see what you mean with having to set some header props and potentially the header type from within the a page.
Just noted a few code style issues.

2022-03-17 11:14 UTC, ShynRou commented on src/app/containers/PageContainer/context/actions.ts
> +        }),
Same as comment above

2022-03-17 11:14 UTC, ShynRou commented on src/app/containers/PageContainer/PageContainer.tsx
> +  useLayoutEffect(() => {
There is no need for this to run after rendering.
```suggestion
  useEffect(() => {
```

2022-03-17 11:14 UTC, ShynRou commented on src/app/containers/PageContainer/PageContainer.tsx
> +        return <></>; // todo
```suggestion
      case HeaderTypes.DEFAULT:
        return <DefaultHeaderComponent {...options.headerProps} />;
      case HeaderTypes.FAST_BTC:
        return <FastBtcHeader address={options.headerProps?.address} />;
      case HeaderTypes.CROSS_CHAIN:
        return <UserWallet address={options.headerProps?.address} />;
      case HeaderTypes.LABS:
        return <></>; // todo
      default:
        return null;
```

2022-03-17 11:14 UTC, ShynRou commented on src/app/containers/PageContainer/PageContainer.tsx
> +        return null;
```suggestion
      default:
        return null;
```

2022-03-18 12:03 UTC, JoeStorm99 submitted a review, later dismissed

2022-03-18 12:10 UTC, Alitasovryn commented
FastBTC header

2022-03-18 12:13 UTC, Alitasovryn commented
FastBTC header 
<img width="1420" alt="Screen Shot 2022-03-18 at 7 47 52 AM" src="https://user-images.githubusercontent.com/94629682/159000763-a5fd9738-aa9e-4859-9fc7-af595c8433f8.png">

Crosschain header
<img width="1426" alt="Screen Shot 2022-03-18 at 8 07 33 AM" src="https://user-images.githubusercontent.com/94629682/159000825-385702a2-874d-4246-8b94-80ec583a5898.png">

FastBTC header has **Back to portfolio** but cross chain header shows **Back.** It would be nice if both header looks similar.

2022-03-18 15:25 UTC, Alitasovryn submitted a review, later dismissed

2022-03-21 12:07 UTC, ShynRou approved these changes

2022-03-24 08:43 UTC, merged