[Switch] - switch cleanup
DistributedCollective/Sovryn-frontend pull request #2127
Opened 2022-04-11 06:53 UTC by pietro-maximoff

https://sovryn.monday.com/boards/2218344956/pulses/2430716176

2022-04-11 15:12 UTC, tiltom requested changes

2022-04-11 15:12 UTC, tiltom commented on src/app/components/Switch/index.module.scss
> +.switchLabel {
```suggestion
.label {
```

2022-04-12 06:48 UTC, tiltom approved these changes

2022-04-12 13:01 UTC, creed-victor approved these changes

2022-04-12 14:59 UTC, merged