Feat/2415405512 dropdown atomic component
DistributedCollective/Sovryn-frontend pull request #2143
Opened 2022-04-18 19:50 UTC by pietro-maximoff

https://sovryn.monday.com/boards/2218344956/pulses/2415405512

2022-04-19 13:25 UTC, tiltom requested changes

2022-04-19 13:25 UTC, tiltom commented on src/app/components/Dropdown/index.tsx
> +    const DropdownPosition = {
You can extract it to a function outside the component (with `coords` and `mode` as parameters).

2022-04-19 13:25 UTC, tiltom commented on src/app/components/Dropdown/index.tsx
> +        color && styles[color],
```suggestion
        color,
```

2022-04-19 13:25 UTC, tiltom commented on src/app/components/Dropdown/index.tsx
> +    const coords = getCoords();
```suggestion
    if (!isOpen) {
       return;
    }
    
    const coords = getCoords();
```

2022-04-19 13:25 UTC, tiltom commented on src/app/components/Dropdown/index.tsx
> +        color && styles[color],
You can make this adjustment once you adjust `DropdownColor` enum.

2022-04-19 13:25 UTC, tiltom commented on src/app/components/Dropdown/index.tsx
> +              color && styles[color],
```suggestion
              color,
```

2022-04-19 13:25 UTC, tiltom commented on src/app/hooks/useOnClickOutside.ts
> +        !shouldIgnoreByRef && callback(event);
```suggestion
        if(!shouldIgnoreByRef) {
           callback(event);
        }
```

2022-04-19 15:02 UTC, ShynRou commented on src/app/components/Dropdown/index.module.scss
> +.dropdown {
It is correct this way, as the element this belongs to also applies the className prop. Without using a module.scss class you cannot override the css rules properly neither with tailwind nor normal classes passed into the classNames property.
This is an issue we have on multiple already existing components.

2022-04-20 14:08 UTC, ShynRou approved these changes

2022-04-22 12:03 UTC, creed-victor approved these changes

2022-04-22 12:05 UTC, tiltom approved these changes

2022-04-23 08:22 UTC, merged