feat: universal dialog component
DistributedCollective/Sovryn-frontend pull request #2151
Opened 2022-04-21 13:35 UTC by creed-victor

https://sovryn.monday.com/boards/2218344956/pulses/2236624785

Example is in https://feat-refactor-dialog.sovryn.pages.dev/storybook?path=/story/molecule-dialog

Note: had to make close button / icon smaller than it was, otherwise it's going out of viewport on smaller screens (because it's outside of dialog for non-mobile devices)

2022-04-22 09:08 UTC, JoeStorm99 submitted a review, later dismissed

2022-04-22 12:37 UTC, tiltom requested changes

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.module.scss
> +    @apply tw-flex tw-flex-col tw-justify-center tw-items-center;
```suggestion
    @apply tw-fixed tw-inset-0 tw-flex tw-flex-col tw-justify-center tw-items-center;
```

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.tsx
> +interface DialogFunctionComponent<T = {}> extends FunctionComponent<T> {
```suggestion
interface IDialogFunctionComponent<T = {}> extends FunctionComponent<T> {
```

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.tsx
> +interface DialogFunctionComponent<T = {}> extends FunctionComponent<T> {
Create `types.ts` file and extract this, `DialogSize` and `sizeMap` to it.

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.tsx
> +  }, [onClose]);
```suggestion
const handleClose = useCallback(() => {
    onClose?.();
  }, [onClose]);
```

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.module.scss
> +.dialog_wrapper {
```suggestion
.wrapper {
```

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.module.scss
> +.dialog_container {
```suggestion
container {
```

2022-04-22 12:37 UTC, tiltom commented on src/app/components/Dialog/index.module.scss
> +.close_button {
```suggestion
.closeButton {
```

2022-04-25 09:18 UTC, tiltom submitted a review, later dismissed

2022-05-02 09:14 UTC, creed-victor commented on src/app/components/Dialog/types.ts
> +}
Not sure I understood. It's static variable which tracks how many dialogs was opened, so if you would open another dialog while one is already opened - newest would appear on top of the previous one

2022-05-05 09:20 UTC, JoeStorm99 submitted a review, later dismissed

2022-05-08 14:49 UTC, soulBit requested changes
Generally looks good but few things to check before I approve:

1. Point 6a in the spec indicates we should have sizes for `2-7xl` but we only have up to 3 in this PR
2. Point 6c in the spec doesn't seem to be implemented here

@ShynRou if the above two points are fine then let's update the spec to match

I've also made a small fix to the `DialogSize` enum so that the size values appear correctly in Storybook (they were appearing as indexes previously).

2022-05-09 07:48 UTC, creed-victor commented
> 1. Point 6a in the spec indicates we should have sizes for `2-7xl` but we only have up to 3 in this PR

Added missing sizes

> 2. Point 6c in the spec doesn't seem to be implemented here

It's implemented but you need to change your storybook preview width to the mobile device (xs size)

2022-05-09 08:41 UTC, tiltom approved these changes

2022-05-09 16:37 UTC, soulBit approved these changes

2022-05-09 19:34 UTC, JoeStorm99 approved these changes

2022-05-10 07:40 UTC, merged