Feat: zero beta portfolio
DistributedCollective/Sovryn-frontend pull request #2153
Opened 2022-04-22 06:43 UTC by ShynRou

Resolves https://sovryn.monday.com/boards/2218344956/pulses/2507858908

NUE no longer needed to be added.

2022-04-22 11:33 UTC, creed-victor requested changes

2022-04-22 11:33 UTC, creed-victor commented on src/app/components/SovGenerationNFTS/index.tsx
> +        {!items?.length && !tiers?.length && balanceBday === '0' && (
Maybe also add `loading` check from `useLoadSovNfts` and `useCacheCallWithValue` (for community tiers). Currently it shows that user has no NFTs while it's being loaded

2022-04-22 11:33 UTC, creed-victor commented on src/utils/blockchain/contracts.testnet.ts
> +    abi: ZUSDAbi,
At this point dapp only supports ERC20 capabilities for ZUSD token, so you can just reuse erc20TokenAbi

2022-04-22 11:33 UTC, creed-victor commented on src/utils/blockchain/contracts.ts
> +import ZUSDAbi from './abi/ZUSDToken.json';
```suggestion
```

2022-04-22 11:33 UTC, creed-victor commented on src/utils/blockchain/contracts.ts
> +    abi: ZUSDAbi,
```suggestion
    abi: erc20TokenAbi,
```

2022-04-22 11:33 UTC, creed-victor commented on src/utils/blockchain/contracts.testnet.ts
> +import ZUSDAbi from './abi/ZUSDToken.json';
```suggestion
```

2022-04-22 11:33 UTC, creed-victor commented on src/utils/blockchain/contracts.testnet.ts
> +    abi: ZUSDAbi,
```suggestion
    abi: erc20TokenAbi,
```

2022-04-22 13:34 UTC, tiltom requested changes

2022-04-22 13:34 UTC, tiltom commented on src/app/components/UserAssets/BridgeLink.tsx
> +          )}
```suggestion
          className={classNames(styles.actionLink, {
            [styles.disabled]: disableWithdrawal,
          })}
```

2022-04-22 13:34 UTC, tiltom commented on src/app/components/UserAssets/index.tsx
> +                  )}
```suggestion
                  className={classNames(styles.actionLink, {
                    [styles.disabled]: tokens === '0',
                  })}
```

2022-04-22 13:34 UTC, tiltom commented on src/app/components/UserAssets/index.tsx
> +              disabled={tokens === '0'}
You use this condition (`tokens === '0'`) on many places, extract it to a variable (e.g. `hasAnyTokens`) and use `useMemo`.

2022-06-06 08:37 UTC, tiltom approved these changes
The code itself looks good but we shouldn't merge it until https://github.com/DistributedCollective/Sovryn-frontend/pull/2224 is in `development` (and its story - https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2629468226 closed) because it contains many adjustments for Portfolio page.

2022-06-15 12:56 UTC, closed without merging