Feat/2255707517 icon atomic component
DistributedCollective/Sovryn-frontend pull request #2159
Opened 2022-04-27 14:08 UTC by pietro-maximoff

https://sovryn.monday.com/boards/2218344956/pulses/2255707517

2022-05-02 08:11 UTC, ShynRou requested changes

2022-05-02 08:11 UTC, ShynRou commented on src/app/components/Icon/index.tsx
> +    </div>
The div wrapper is not needed here, className should be passed directly to FontAwesomeIcon, svg or the customIcon div.
Inline should also set the outer element display to inline-block.

2022-05-02 08:11 UTC, ShynRou commented on src/app/components/Icon/types.ts
> +}
I think these should be constants in the main file and not an enum.

2022-05-02 08:11 UTC, ShynRou commented on src/app/components/Icon/index.tsx
> +  size?: number | string;
```suggestion
  size?: number | SizeProp;
```

2022-05-03 11:59 UTC, creed-victor approved these changes

2022-05-05 21:00 UTC, soulBit approved these changes

2022-05-06 07:37 UTC, tiltom approved these changes

2022-05-08 15:33 UTC, merged