[ACL] - contain fixes for frontend miscellaneous tasks
DistributedCollective/Sovryn-frontend pull request #2161
Opened 2022-04-28 09:37 UTC by pietro-maximoff

https://sovryn.monday.com/boards/2218344956/pulses/2562390754
https://sovryn.monday.com/boards/2218344956/pulses/2562393165
https://sovryn.monday.com/boards/2218344956/pulses/2562400509
https://sovryn.monday.com/boards/2218344956/pulses/2562400706

2022-04-28 11:57 UTC, Alitasovryn commented
<img width="1373" alt="Screen Shot 2022-04-28 at 7 53 54 AM" src="https://user-images.githubusercontent.com/94629682/165746828-4556b913-877a-4126-aa02-ed3615c5c5ee.png">

AC is to ensure rBTC is is properly named as RBTC. Please check

2022-05-03 11:57 UTC, creed-victor requested changes

2022-05-03 11:57 UTC, creed-victor commented on src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
> +                        />
It looks like Launchpad and Claim of origins was put to be visible only on testnet? I think it should be visible on mainnet

2022-05-04 16:43 UTC, Alitasovryn submitted a review, later dismissed

2022-05-05 06:36 UTC, creed-victor approved these changes

2022-05-08 16:07 UTC, soulBit approved these changes
Fixed two small issues with mobile menu:

- data-action-id's that weren't consistent with the main menu id's
- fixed the "help" menu option to the bottom of the menu (it was being placed inside Labs group)

2022-05-08 16:08 UTC, merged