Order History adjustments
DistributedCollective/Sovryn-frontend pull request #2165
Opened 2022-05-02 11:36 UTC by tiltom

2022-05-04 12:52 UTC, ShynRou requested changes

2022-05-04 12:52 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
> +          <span className="tw-text-2xl">-</span>
I would not use a different font size, but rather an en-dash
```suggestion
          <span>–</span>
```

2022-05-04 12:52 UTC, ShynRou commented on src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
> +          <span className="tw-text-2xl">-</span>
See comment below

2022-05-05 06:44 UTC, creed-victor approved these changes

2022-05-05 10:53 UTC, ShynRou approved these changes

2022-05-05 10:53 UTC, merged