Feat/2382474482 perps trade dialog adjustments
DistributedCollective/Sovryn-frontend pull request #2190
Opened 2022-05-09 09:41 UTC by ShynRou

Resolves https://sovryn.monday.com/boards/2218344956/pulses/2382474482

3 known bugs to fix:
- [ ] users are sometimes asked to sign the same digest multiple times 
- [ ] the open orders don't refresh automatically
- [ ] the trade process doesn't seem to catch the transaction result anymore.

2022-05-10 10:53 UTC, tiltom requested changes

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
> +  // {
This is not necessary anymore, is it?

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/contexts/PerpetualQueriesContext.tsx
> +export type PerpetualValue = {
```suggestion
 type PerpetualValue = {
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
> +  const completedTransactions = usePerpetual_completedTransactions();
`Open Orders` table doesn't refresh automatically after new limit/stop trades so this probably doesn't work correctly.

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/hooks/usePerpetual_transaction.ts
> +      let txType: TxType = PerpetualTxMethodTypeMap[transaction.method];
```suggestion
      const txType = PerpetualTxMethodTypeMap[transaction.method];
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/types.ts
> +  /** trigger quote trigger wei string */
```suggestion
  /** trigger quote price as wei string */
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/contractUtils.tsx
> +    0, // TODO: this is fTriggerPrice, it will need to be adjusted once we have limit orders functionality, it's 0 for market orders
```suggestion
    0,
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/contractUtils.tsx
> +  context: PerpetualQueriesContextValue,
```suggestion
 
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/contractUtils.tsx
> +  context: PerpetualQueriesContextValue,
Unused arg.

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/contractUtils.tsx
> +): Promise<Parameters<SendTxResponseInterface['send']>[0]> => {
```suggestion
const perpetualCancelLimitTradeArgs = async (
  transaction: PerpetualTxCancelLimitOrder
): Promise<Parameters<SendTxResponseInterface['send']>[0]> => {
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/contractUtils.tsx
> +): Promise<Parameters<SendTxResponseInterface['send']>[0]> => {
Unused args.

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/perpUtils.ts
> +  const NAME = toUtf8Bytes('Perpetual Trade Manager');
```suggestion
  const name = toUtf8Bytes('Perpetual Trade Manager');
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/perpUtils.ts
> +  const DOMAIN_TYPEHASH = keccak256(
```suggestion
  const domainTypehash = keccak256(
```

2022-05-10 10:53 UTC, tiltom commented on src/app/pages/PerpetualPage/utils/perpUtils.ts
> +  const TRADE_ORDER_TYPEHASH = keccak256(
```suggestion
  const tradeOrderTypehash = keccak256(
```

2022-05-10 10:53 UTC, tiltom commented on src/locales/en/translation.json
> +        "OrderSize": "Order Size:"
```suggestion
        "orderSize": "Order Size:"
```

2022-05-10 14:55 UTC, ShynRou commented on src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
> +  // {
Correct, sorry forgot to re-enable it.

2022-05-11 07:47 UTC, tiltom approved these changes

2022-05-11 11:10 UTC, merged