[BorrowPage] add data-action-ids
DistributedCollective/Sovryn-frontend pull request #2202
Opened 2022-05-13 07:22 UTC by ShynRou

Resolves https://sovryn.monday.com/boards/2218344956/pulses/2592960099

2022-05-16 14:13 UTC, tiltom submitted a review, later dismissed

2022-05-19 10:17 UTC, creed-victor approved these changes

2022-05-20 11:31 UTC, soulBit requested changes
Collateral assets in the dropdown do not have data-action-id's propagated down to them (and seem to be missing the asset name also):
![image](https://user-images.githubusercontent.com/765825/169519797-f964c741-56d6-403d-a201-16379fa66d4e.png)

other changes seem good 👍🏻

2022-05-23 15:59 UTC, Alitasovryn submitted a review, later dismissed

2022-05-25 15:54 UTC, soulBit approved these changes

2022-05-25 16:13 UTC, JoeStorm99 approved these changes

2022-05-25 16:21 UTC, merged