Fix/repay borrow
DistributedCollective/Sovryn-frontend pull request #2214
Opened 2022-05-19 13:50 UTC by creed-victor

https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2668513932

2022-05-20 04:56 UTC, tiltom requested changes

2022-05-20 04:56 UTC, tiltom commented on src/utils/classifiers.ts
> +export const TINY_POSITION_AS_RBTC = 250000000000000;
```suggestion
export const TINY_POSITION_RBTC_VALUE = 250000000000000;
```

2022-05-20 04:56 UTC, tiltom commented on src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
> +  const { value: remainingPrincipalAsRBTC } = useDenominateAssetAmount(
```suggestion
  const { value: remainingPrincipalRBTCValue } = useDenominateAssetAmount(
```

2022-05-20 04:56 UTC, tiltom commented on src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
> +  const askToClosePosition = useMemo(() => {
```suggestion
  const isLeavingTinyPosition = useMemo(() => {
```

2022-05-20 07:34 UTC, tiltom requested changes

2022-05-20 07:34 UTC, tiltom commented on src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
> +  const { value: remainingPrincipalAsRBTCValue } = useDenominateAssetAmount(
```suggestion
  const { value: remainingPrincipalRBTCValue } = useDenominateAssetAmount(
```

2022-05-20 07:34 UTC, tiltom commented on src/utils/classifiers.ts
> +export const TINY_POSITION_AS_RBTC_VALUE = 250000000000000;
```suggestion
export const TINY_POSITION_RBTC_VALUE = 250000000000000;
```

2022-05-20 08:02 UTC, tiltom approved these changes

2022-05-20 11:00 UTC, pietro-maximoff approved these changes

2022-05-25 15:50 UTC, soulBit approved these changes

2022-06-10 16:17 UTC, merged