Feat/2753828948 stake graphql endpoint
DistributedCollective/Sovryn-frontend pull request #2284
Opened 2022-06-23 04:55 UTC by pietro-maximoff

https://sovryn.monday.com/boards/2218344956/pulses/2753828948?doc_id=2753832200

2022-06-27 23:13 UTC, soulBit requested changes

2022-06-28 09:44 UTC, soulBit submitted a review, later dismissed

2022-06-29 14:25 UTC, tiltom commented on src/app/containers/StakePage/components/HistoryEventsTable/HistoryEventRow.tsx
> +  const getActionName = (action: StakeHistoryAction) => {
Extract this function outside of the component.

2022-06-29 14:26 UTC, tiltom commented on src/app/containers/StakePage/components/HistoryEventsTable/HistoryEventRow.tsx
> +  const dollarValue = useMemo(() => {
Use `useDollarValue` hook instead.

2022-06-29 14:29 UTC, tiltom commented on src/app/containers/StakePage/hooks/useGetStakeHistory.ts
> +  return useGetStakeHistoryQuery({
```suggestion
  }, [page, pageSize]);
  
  return useGetStakeHistoryQuery({
```

2022-07-01 13:20 UTC, tiltom submitted a review, later dismissed

2022-07-05 00:00 UTC, soulBit submitted a review, later dismissed

2022-08-03 15:31 UTC, merged