Feat/landing endpoint migration
DistributedCollective/Sovryn-frontend pull request #2286
Opened 2022-06-24 08:57 UTC by Rickk137

2022-06-24 08:58 UTC, Rickk137 commented
still Microservice query 6 is not deployed

2022-06-27 09:55 UTC, soulBit requested changes

2022-06-27 09:55 UTC, soulBit commented on src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
> +    },
```suggestion
    },
    pollInterval: APOLLO_POLL_INTERVAL,
```

this can be imported from `utils/classifiers.ts`

2022-06-27 13:39 UTC, soulBit submitted a review, later dismissed
@rick23p I noticed one small issue that I fixed in the Graph query - sorting history items by timestamp - rest of the changes look good 👍🏻

2022-06-27 18:43 UTC, Alitasovryn submitted a review, later dismissed

2022-07-14 09:34 UTC, pietro-maximoff commented
i can't test https://deploy-preview-2286--legacy-dapp.netlify.app//yield-farm page, its not loaded for me (error Uncaught ReferenceError: Highcharts is not defined) and the same on my local machine

2022-07-19 08:47 UTC, tiltom commented
> i can't test https://deploy-preview-2286--legacy-dapp.netlify.app/yield-farm page, its not loaded for me (error Uncaught ReferenceError: Highcharts is not defined) and the same on my local machine

@Rickk137 ?

2022-07-20 12:18 UTC, Rickk137 commented
> i can't test https://deploy-preview-2286--legacy-dapp.netlify.app/yield-farm page, its not loaded for me (error Uncaught ReferenceError: Highcharts is not defined) and the same on my local machine

I'm not Sure what's the issue here, SInce it was running fine for @soulBit 
I need to dive more into it

2022-07-21 11:14 UTC, Rickk137 commented
@tiltom @pietro-maximoff 
Could you retry, i think the issue should be resolved

2022-07-22 08:35 UTC, tiltom commented
> @tiltom @pietro-maximoff Could you retry, i think the issue should be resolved

The Highchart issue is not happening again, thanks.

2022-07-22 09:53 UTC, pietro-maximoff commented
i tested and all values seems the same, but the thing is that i can't see all of my history events in Liquidity History table, it shows me only 10 items instead of 22 that i can see in response
<img width="1561" alt="page1" src="https://user-images.githubusercontent.com/74987028/180414321-e77320bd-8af5-490e-8d71-5ae271278518.png">
<img width="1588" alt="page2" src="https://user-images.githubusercontent.com/74987028/180414352-2c043da1-dd3d-4936-99c3-2044185b9c54.png">
![response](https://user-images.githubusercontent.com/74987028/180414386-f9f93e10-ac13-44ae-afe4-697d06de6ef2.png)

2022-07-22 11:41 UTC, tiltom commented
> I tested and all the values look the same, but the thing is that i can't see all of my history events in Liquidity History table, it shows me only 10 items instead of 22 that i can see in response <img alt="page1" width="1561" src="https://user-images.githubusercontent.com/74987028/180414321-e77320bd-8af5-490e-8d71-5ae271278518.png"> <img alt="page2" width="1588" src="https://user-images.githubusercontent.com/74987028/180414352-2c043da1-dd3d-4936-99c3-2044185b9c54.png"> ![response](https://user-images.githubusercontent.com/74987028/180414386-f9f93e10-ac13-44ae-afe4-697d06de6ef2.png)
> 
> UPDATE seems that the data is filtered the rows that we can't find the contract assets, so its fine as i can see

Ok, thanks for testing @pietro-maximoff :) It has been already tested by Alita as well so I'll send it to @soulBit to doublecheck once he's back.

2022-07-22 15:26 UTC, pietro-maximoff commented on src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
>  const pageSize = 6;
change pls to 5 since we use now 5 items per page

2022-07-23 15:13 UTC, soulBit approved these changes

2022-07-24 06:28 UTC, pietro-maximoff approved these changes

2022-07-25 12:00 UTC, Alitasovryn approved these changes

2022-07-25 14:59 UTC, merged