Feat/cross chain restyle
DistributedCollective/Sovryn-frontend pull request #2287
Opened 2022-06-24 08:58 UTC by Rickk137

2022-07-17 13:14 UTC, tiltom requested changes

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.tsx
> +                    value={`${toNumberFormat(
For the `value`, pls use `AssetValue` component.

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.tsx
> +              {bridgeBalance.value !== false && (
I don't get why the `bridgeBalance.value` is either `string` or `false`. Instead of `false`, assign `0` (or `null`).

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.tsx
>  const Table = styled.table`
Use CSS modules.

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/BridgeWithdrawPage/components/ReceiverSelector/index.tsx
> +            label={`Receiving ${targetAsset} Address`}
Use a localized string.

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/BridgeWithdrawPage/components/SidebarSteps/index.tsx
> +        Choose <br />
Use localized strings for titles.

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/FastBtcPage/components/AggregatorWithdraw/AmountForm.tsx
> +        <WithdrawDetails className="tw-bg-transparnet" network={network} />
```suggestion
        <WithdrawDetails className="tw-bg-transparent" network={network} />
```

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
> +      value: <>{toNumberFormat(amount, 8)} BTC</>,
Use `AssetValue` component (for all values in this file).

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/FastBtcPage/components/Withdraw/ReviewScreen.tsx
> +          {toNumberFormat(amount, 8)} <AssetSymbolRenderer asset={asset} />
Use `AssetValue` component.

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/FastBtcPage/components/Withdraw/StatusScreen.tsx
> +          {toNumberFormat(amount, 8)} <AssetSymbolRenderer asset={asset} />
Use `AssetValue` component.

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/ReciveRBTCPage/index.tsx
> +export const ReciveRBTCPage: React.FC = () => {
```suggestion
export const RecieveRBTCPage: React.FC = () => {
```

2022-07-17 13:14 UTC, tiltom commented on src/app/pages/ReciveRBTCPage/index.tsx
> +        <title>{t(translations.reciveRBTCPage.title)}</title>
```suggestion
        <title>{t(translations.recieveRBTCPage.title)}</title>
```

2022-07-18 09:10 UTC, Rickk137 commented on src/app/components/CrossChain/CrossChainLayout.tsx
> +  const blockieImage = useMemo(() => {
The two other places are not being used, i'll delete the unused components

2022-07-18 09:11 UTC, Rickk137 commented
> ### Notes from my testing
> ### Send token (other than RBTC)
> * Stages progress bar has different styling than in the Figma (texts should be aligned to the left and it should be a continuous line).
> * In case the stage shouldn’t be clickable, we shouldn’t display it as `cursor: pointer` (and I think that the whole area needs to be clickable, not only the text).
> * Confirm buttons in almost all of the steps have different styling than in the Figma design.
> * `Processing transaction` dialog and `Transaction completed` dialog contain different fields than they should.
> 
> <img alt="Destination" width="836" src="https://user-images.githubusercontent.com/14878713/178742774-2eeec1db-5d88-4974-8ec6-025d54068c83.png">
> 
> ### Receive token (other than RBTC)
> * Second stage label should be `Wallet` and not `Select Wallet`.
> * `Wallet` step looks different than in the Figma design.
> * `Enter Address` stage is missing.
> * `Review Transaction` step doesn’t contain `Receiver` info.
> * `Processing transaction` dialog and `Transaction completed` dialog contain different fields than they should.
> 
> ### Fast BTC send
> * The copy on the first step is slightly different than in the Figma (also submit button design and `contact us` link have different styling).
> * Stages steps have different styling than in the Figma design.
> * There is no `Back to portfolio` button in the `Processing Transaction` stage in the design and it’s definitely not necessary as we have it always visible in the top left corner.
> * `Transaction Completed` stage shouldn’t contain the message about withdrawal being processed.
> 
> <img alt="Transaction" width="729" src="https://user-images.githubusercontent.com/14878713/178743814-7dd83886-cea6-4859-8eac-f798cb4c6e9c.png">
> 
> ### Fast BTC receive
> * Wrong subtitle in the first step.
> * The name of the second stage (`Enter Address`) doesn’t make any sense as there is no address to enter, this step just displays you the QR and address to send BTC to.
> * Again, there is no need for `Back to portfolio` button in `Processing Transaction` and `Transaction Completed` steps.
> * Don’t show “Your deposit is being processed” message in the last step.

Gilad and Plily has reviewed the UI and made some changes that are not applied in the figma. But they are happy with the current implementation.
If there is something that you think must change we should have a discussion with them

2022-07-18 09:13 UTC, Rickk137 commented on src/app/components/Stepper/Step.tsx
> +};
not sure what should be changed here?

2022-07-19 10:34 UTC, tiltom commented on src/app/components/Stepper/Step.tsx
> +};
You have unnecessary `return` there,

2022-07-19 12:27 UTC, tiltom commented
@Rickk137 Changes discussed with Pili and Gilad:

- FastBTC Receive - Change "Enter Address" label to "BTC Address".
<img width="989" alt="image" src="https://user-images.githubusercontent.com/14878713/179749527-17c0e277-106d-41ad-8510-1f7cba793eed.png">

- Do not show "Your deposit/withdrawal is being processed" message in the last step where everything is confirmed.

2022-07-21 15:00 UTC, tiltom requested changes

2022-07-28 12:33 UTC, tiltom approved these changes

2022-08-01 14:25 UTC, Alitasovryn submitted a review, later dismissed

2022-08-03 14:35 UTC, soulBit approved these changes

2022-08-03 14:36 UTC, merged