feat: migrate trading endpoints
DistributedCollective/Sovryn-frontend pull request #2298
Opened 2022-06-29 15:41 UTC by Rickk137

2022-07-06 16:58 UTC, soulBit commented
Identified an issue with mainnet TVL data compared to live dapp, raised this with Shadow and will need to have that resolved before QA can test

2022-07-13 09:38 UTC, soulBit requested changes
Two small changes to make - I also spotted an inconsistency with the TVL data vs live dapp, I will query that on Monday story

2022-07-13 09:38 UTC, soulBit commented on src/app/pages/BuySovPage/components/InfoBar/index.tsx
> +  console.log('circulating_supply:', totalSupply);
```suggestion
```

2022-07-13 09:38 UTC, soulBit commented on src/app/pages/LandingPage/index.tsx
> +        console.log('pair:", res.data', res.data);
```suggestion
```

2022-07-18 08:46 UTC, tiltom requested changes

2022-07-18 08:46 UTC, tiltom commented on src/app/hooks/useGetTokenPrice.tsx
> +export const useGetTokenPrice = (asset: Asset, type: 'BTC' | 'USD' = 'BTC') => {
I don't like `type` typing - pls extract it to an enum that can stay in this file (you can call it `DenominationAsset`).

2022-07-18 08:46 UTC, tiltom commented on src/app/hooks/useGetTokenPrice.tsx
> +      .toFixed(4);
I am not sure about this, I think you want to have the price as precise as possible and you only need to round it when displaying it.

2022-07-21 12:03 UTC, tiltom requested changes
The code itself is fine but I see completely different data on testnet. Take a look at it pls and consult with @BetsyBraddock if needed. Also, as Betsy already mentioned in the story's comment, order crypto prices by marketcap.

New implementation:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/14878713/180208730-9c2032f9-a1d5-4f06-840c-fa1dbf501276.png">
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/14878713/180208794-74a3ed0a-4236-407a-ae05-41e309e4c964.png">

Existing implementation:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/14878713/180208884-00b46d40-138c-4852-86dd-02448b5bcc54.png">
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/14878713/180208952-ea3441bf-4e44-4b93-b087-635f9c550db9.png">

2022-07-22 14:21 UTC, tiltom submitted a review, later dismissed

2022-07-22 16:05 UTC, Alitasovryn approved these changes

2022-07-23 15:31 UTC, soulBit approved these changes

2022-07-25 10:00 UTC, tiltom requested changes

2022-07-25 10:05 UTC, tiltom approved these changes

2022-07-25 16:48 UTC, merged