[Reward] - update reward endpoint part 2
DistributedCollective/Sovryn-frontend pull request #2327
Opened 2022-07-13 03:10 UTC by pietro-maximoff

https://sovryn.monday.com/boards/2218344956/pulses/2852587684

2022-07-13 13:35 UTC, soulBit approved these changes

2022-07-21 14:03 UTC, tiltom requested changes

2022-07-21 14:03 UTC, tiltom commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
>                      <span className="tw-mr-1">...</span> {asset}
Use `AssetValue` component.

2022-07-21 14:03 UTC, tiltom commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
>                    <span className="tw-mr-1">...</span> {asset}
Use `AssetValue` component.

2022-07-21 14:05 UTC, tiltom commented
Testnet inconsistencies, @BetsyBraddock and @pietro-maximoff , pls take a look at it.

New implementation:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/14878713/180233321-47f98786-6001-474b-8b79-593abdf1cb9c.png">

Existing implementation:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/14878713/180233445-905f3d4e-dbfc-4c7b-9534-60e815a53134.png">

2022-07-21 15:06 UTC, Alitasovryn submitted a review, later dismissed

2022-07-22 08:31 UTC, tiltom requested changes

2022-07-22 08:31 UTC, tiltom commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
> +                    />
```suggestion
                    <AssetValue
                      value={Number(availableAmount)}
                      minDecimals={6}
                      maxDecimals={6}
                      assetString={asset}
                      mode={AssetValueMode.auto}
                      isApproximation={showApproximateSign}
                    />
```

2022-07-22 08:31 UTC, tiltom commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
>                      {showApproximateSign && '≈ '}
```suggestion

```

2022-07-22 08:31 UTC, tiltom commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
> +                  />
```suggestion
                  <AssetValue
                    value={Number(totalEarnedAmount)}
                    minDecimals={6}
                    maxDecimals={6}
                    assetString={asset}
                    mode={AssetValueMode.auto}
                    isApproximation={showApproximateSign}
                  />
```

2022-07-22 08:31 UTC, tiltom commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
>                    {showApproximateSign && '≈ '}
```suggestion

```

2022-07-22 14:42 UTC, tiltom approved these changes

2022-07-23 14:59 UTC, soulBit requested changes

2022-07-23 14:59 UTC, soulBit commented on src/app/pages/RewardPage/components/RewardsDetail/index.tsx
> +                      value={Number(availableAmount)}
Due to the `weiToXX()` formatting calls being omitted here now, the fees totals shown on Fees Earned tab are broken - please update `src\app\pages\RewardPage\components\FeesEarnedTab\index.tsx` with the following change (addition of `weiTo18()`'s):

```
 <RewardsDetail
          color={RewardsDetailColor.Yellow}
          title={t(translations.rewardPage.fee.stakingFee)}
          availableAmount={weiTo18(amountToClaim)}
          totalEarnedAmount={weiTo18(totalRewardsEarned)}
          asset={Asset.RBTC}
          loading={totalAmountLoading}
          showApproximateSign
        />
```

2022-07-25 14:46 UTC, merged