Perpetuals - new rankings
DistributedCollective/Sovryn-frontend pull request #2356
Opened 2022-08-03 12:52 UTC by tiltom

Resolves https://sovryn.monday.com/boards/2218344956/pulses/2988537808

2022-08-17 17:24 UTC, soulBit requested changes
Only minor changes required

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/hooks/useGetData.ts
> +          setLoaded(true);
Move `setLoaded(true)` calls from these promise handlers into a `finally()`

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/hooks/useGetData.ts
> +              val => val.walletAddress.toLowerCase() === account.toLowerCase(),
```suggestion
              val => val.walletAddress.toLowerCase() === account?.toLowerCase(),
```

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/hooks/useGetData.ts
> +        setLoaded(true);
Move `setLoaded(true)` calls into `.finally()`

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/hooks/useGetData.ts
> +        setLoaded(true);
Move `setLoaded(true)` calls into `.finally()`

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/hooks/useGetData.ts
> +        setLoaded(true);
Move `setLoaded(true)` calls into `.finally()`

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/hooks/useGetData.ts
> +            row => row.walletAddress.toLowerCase() === account.toLowerCase(),
Use `account?.toLowerCase()`

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestVolumeTable/hooks/useGetData.ts
> +            row => row.walletAddress.toLowerCase() === account.toLowerCase(),
```suggestion
            row => row.walletAddress.toLowerCase() === account?.toLowerCase(),
```

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/MostTradesTable/hooks/useGetData.ts
> +            row => row.walletAddress.toLowerCase() === account.toLowerCase(),
```suggestion
            row => row.walletAddress.toLowerCase() === account?.toLowerCase(),
```

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/MostTradesTable/hooks/useGetData.ts
> +        setLoaded(true);
Move `setLoaded(true)` calls into `.finally()`

2022-08-17 17:24 UTC, soulBit commented on src/app/pages/PerpetualPage/hooks/graphql/useGetRealizedPnlData.ts
> +  //console.log(traderDataQuery?.data);
```suggestion
```

2022-08-18 07:38 UTC, tiltom commented on src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/hooks/useGetData.ts
> +          const trader = leaderboardData?.traders.find(
No possibility, because I have a check if `leaderboard` data are defined on line 47 and in case they are, `traders` is the topmost property of it.

2022-08-18 10:39 UTC, merged