Fix/migration deployment fix
DistributedCollective/Sovryn-frontend pull request #2382
Opened 2022-08-09 08:58 UTC by pietro-maximoff

added a fix for PairNavbar Selector related to this PR https://github.com/DistributedCollective/Sovryn-frontend/pull/2298
this task https://sovryn.monday.com/boards/2218344956/pulses/2731931003/posts/1641113880 related to this fix as well

2022-08-09 14:57 UTC, soulBit requested changes
Revert changes to `src/utils/blockchain/abi/sovrynProtocol.json` , this is not merged from https://github.com/DistributedCollective/Sovryn-frontend/pull/2368 yet

2022-08-16 13:52 UTC, tiltom approved these changes

2022-08-18 13:00 UTC, creed-victor approved these changes

2022-08-23 17:15 UTC, soulBit approved these changes

2022-09-06 15:35 UTC, Alitasovryn approved these changes

2022-09-06 15:37 UTC, merged