feat: update XUSD lend pool rewards
DistributedCollective/Sovryn-frontend pull request #2405
Opened 2022-09-02 07:50 UTC by soulBit

https://sovryn.atlassian.net/browse/SOV-428

2022-09-02 10:41 UTC, tiltom requested changes

2022-09-02 10:41 UTC, tiltom commented on src/app/components/Promotions/index.tsx
> +          {/* <PromotionCard
I'd probably just delete all of the commented out promotions (if we know we don't want to bring them back soon).

2022-09-05 08:22 UTC, tiltom approved these changes

2022-09-05 12:02 UTC, soulBit commented
This has been approved by QA

2022-09-05 12:02 UTC, merged