Trading pair rates migration
DistributedCollective/Sovryn-frontend pull request #2434
Opened 2022-10-13 13:16 UTC by tiltom

Resolves https://sovryn.atlassian.net/browse/SOV-781

2022-10-14 09:56 UTC, soulBit submitted a review, later dismissed

2022-10-14 15:37 UTC, creed-victor requested changes

2022-10-17 08:46 UTC, tiltom commented on src/app/pages/RewardPage/index.tsx
> +  usePriceFeeds_tradingPairRates();
That was the intent but I missed some dependencies, it's reverted now.

2022-10-17 09:08 UTC, soulBit approved these changes

2022-10-17 11:59 UTC, creed-victor approved these changes

2022-10-17 13:28 UTC, merged