SOV-1141: fixing the transak integration
DistributedCollective/Sovryn-frontend pull request #2461
Opened 2022-12-02 10:55 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1141

2022-12-03 09:57 UTC, tiltom requested changes
I found several issues (on testnet) during my testing:

1. The FastBTC address is not prefilled and I get the following error.
<img width="693" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/14878713/205434862-63ef2c06-1730-494b-b2fc-cdd31bf323fe.png">

2. Once Transak popup is active, I cannot close it.

3. I don't think that all of the texts in the FastBTC part of the flow are correct (they need adjustments). Discuss them with Pili pls.
![image](https://user-images.githubusercontent.com/14878713/205435088-1b66471e-64ac-4320-af73-01876de49f84.png)

![image](https://user-images.githubusercontent.com/14878713/205435128-b19fbbb3-713d-4d98-a713-d134b3818c4b.png)

2022-12-03 09:57 UTC, tiltom commented on src/app/components/TransakDialog/TransakScreen.tsx
> +  const handleTransakClick = useCallback(() => handleClick('RBTC'), [
Since `RBTC` is not supported, I suppose you should change it to `BTC`.

2022-12-03 09:57 UTC, tiltom commented on src/app/components/TransakDialog/useTransak.ts
> +    currency: 'RBTC',
```suggestion
    currency: 'BTC',
```

2022-12-03 09:57 UTC, tiltom commented on src/app/components/TransakDialog/useTransak.ts
> +        console.log('market as done', orderData);
```suggestion
        console.log('marked as done', orderData);
```

2022-12-03 09:57 UTC, tiltom commented on src/app/pages/FastBtcPage/components/Deposit/AddressForm.tsx
> +        {type === FastBtcDirectionType.TRANSAK && (
Extract this condition to a variable (e.g. `isTransakDeposit`), use `useMemo` and use it here and on the line `32` as well.

2022-12-03 09:57 UTC, tiltom commented on src/app/pages/FastBtcPage/containers/DepositContainer.tsx
> +  type = FastBtcDirectionType.DEPOSIT,
```suggestion
  type,
```
No need to provide a default value if `type` is mandatory.

2022-12-03 10:10 UTC, grinry commented
> 1. The FastBTC address is not prefilled and I get the following error.

That's expected behaviour - transak does not support testnet btc addresses so it csn only be tested on production env (will prepare deployment for staging).

> 2. Once Transak popup is active, I cannot close it.

Will try debugging, looks like transak api does not send close event anymore.


> 3. I don't think that all of the texts in the FastBTC part of the flow are correct (they need adjustments). Discuss them with Pili pls.

Users are subject to the rules of the fastbtc and they will be sending BTC to receive RBTC.
So all texts here are true, but could be reworded maybe with better explaination of what will happen next

2022-12-05 11:16 UTC, creed-victor commented
Tests should be done on staging env: https://feat-sov-1141-fixing-the-transak-integration--legacy-dapp.netlify.app/

2022-12-05 12:35 UTC, tiltom requested changes

2022-12-05 12:35 UTC, tiltom commented on src/app/components/TransakDialog/useTransak.ts
> +        console.log('transak::success', orderData);
Delete this debug code.

2022-12-05 12:35 UTC, tiltom commented on src/app/components/TransakDialog/useTransak.ts
> +        console.log('transak::closed', event);
Delete pls.

2022-12-05 13:12 UTC, tiltom approved these changes

2022-12-06 11:24 UTC, pietro-maximoff commented
@creed-victor are there any updates regarding Tiltom's comment "Once Transak popup is active, I cannot close it." I also can't close it. other stuff looks good

2022-12-06 11:36 UTC, pietro-maximoff approved these changes

2022-12-07 19:53 UTC, LunaSov approved these changes

2022-12-08 11:55 UTC, merged