fix: SOV-1606 ugly liquality error message
DistributedCollective/Sovryn-frontend pull request #2510
Opened 2023-03-23 11:58 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1606

2023-03-24 14:36 UTC, tiltom requested changes

2023-03-24 14:36 UTC, tiltom commented on src/app/components/TransactionDialog/TxRequestDialog.tsx
> +    return error;
```suggestion
    if (
      error?.includes('User denied transaction signature') ||
      error?.includes('UserDeclinedError')
    ) {
      return t(translations.walletProvider.userDenied);
    }
   
    return error;
```

2023-03-28 09:38 UTC, pietro-maximoff submitted a review, later dismissed

2023-03-28 13:17 UTC, soulBit submitted a review, later dismissed
Nice tidy up @tiltom, approved

2023-03-30 07:55 UTC, merged