SOV-2205: Update Reward SOV amounts for D1 pools
DistributedCollective/Sovryn-frontend pull request #2518
Opened 2023-04-06 15:42 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-2205

2023-04-11 07:00 UTC, creed-victor submitted a review, later dismissed

2023-04-12 07:58 UTC, tiltom requested changes
I agree with @creed-victor, you should pass localized value to translations from components. If that's too difficult, change it to `7.5K` at least.

2023-04-12 08:43 UTC, pietro-maximoff commented
> I agree with @creed-victor, you should pass localized value to translations from components. If that's too difficult, change it to `7.5K` at least.

@tiltom I also agree with that but it needs more time do it, so will change just `,` to `.`

2023-04-12 08:52 UTC, tiltom submitted a review, later dismissed

2023-04-12 08:57 UTC, merged