SOV-2083: add D2 links
DistributedCollective/Sovryn-frontend pull request #2528
Opened 2023-04-26 11:27 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-2083

2023-04-26 19:02 UTC, pietro-maximoff requested changes

2023-04-26 19:02 UTC, pietro-maximoff commented on src/assets/apps-icon.svg
maybe it makes sense to make the icon a bit smaller, for instance, 32px?

2023-04-26 19:02 UTC, pietro-maximoff commented on src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
> +      title: 'sovryn.app',
```suggestion
      title: 'Sovryn.app',
```

2023-04-27 08:02 UTC, tiltom requested changes

2023-04-27 08:02 UTC, tiltom commented on src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
> +          history.push(link.to);
```suggestion
          if (link.hrefExternal) {
            return;
          }

          history.push(link.to);
```

2023-04-27 08:02 UTC, tiltom commented on src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
> +                      href="https://sovryn.app"
Don't forget to change the links here as well.

2023-04-27 12:24 UTC, tiltom submitted a review, later dismissed

2023-04-27 13:56 UTC, pietro-maximoff submitted a review, later dismissed

2023-05-04 15:46 UTC, merged