Feat/liquidity mining
DistributedCollective/Sovryn-frontend pull request #566
Opened 2021-04-01 14:33 UTC by BetsyBraddock

This is the frontend for the liquidity mining campaign. It doesn't change any existing features, just displays to the user their share of the SOV rewards pool:

![image](https://user-images.githubusercontent.com/69518422/113309924-917aec00-92ff-11eb-89de-44f2a822e070.png)
![image](https://user-images.githubusercontent.com/69518422/113309971-9dff4480-92ff-11eb-9dcc-cbc54290fe06.png)

2021-04-01 15:41 UTC, creed-victor requested changes

2021-04-01 15:41 UTC, creed-victor commented on src/app/containers/LiquidityMining/components/EventTable.tsx
> +
```suggestion
```

2021-04-01 15:41 UTC, creed-victor commented on src/app/containers/StatsPage/components/AmmBalance.tsx
> +  const assets = ['DOC', 'USDT', 'BPRO'];
Change these to use Asset.DOC / Asset.USDT / Asset.BPRO to prevent issues if one asset will need to be renamed, removed, etc.

2021-04-01 15:41 UTC, creed-victor commented on src/app/containers/StatsPage/components/AmmStats.tsx
> +  const assets = ['DOC', 'USDT', 'BPRO'];
Use Asset enum here too

2021-04-01 19:05 UTC, grinry approved these changes

2021-04-02 16:52 UTC, merged

2021-04-04 20:14 UTC, bitcoinuser commented
Needs to add the strings of this page to translation file.