[WIP] Switch matomo opt-out to ga opt-out
DistributedCollective/Sovryn-frontend pull request #632
Opened 2021-04-12 22:17 UTC by Bitcoinera

Could not test this on localhost. No GA there

2021-04-13 12:20 UTC, creed-victor commented on src/app/components/Footer/index.tsx
> +              target="_blank"
```suggestion
              target="_blank"
              rel="noopener noreferrer"
```

2021-04-13 12:55 UTC, Bitcoinera commented
This is how it is looking now. Probably should try to make it look fancier

![image](https://user-images.githubusercontent.com/40721795/114555693-3da9c480-9c68-11eb-9f90-8a4cc56316d2.png)

2021-04-13 17:06 UTC, Bitcoinera commented
So it looks like right now

![image](https://user-images.githubusercontent.com/40721795/114592560-5c6d8280-9c8b-11eb-9c2e-4343f2398399.png)

2021-04-13 17:07 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "optOut": "Deixar de participar no <0>Google Analytics</0>",
```suggestion
    "optOut": "Desativar o <0>Google Analytics</0>",
```

2021-04-13 17:07 UTC, bitcoinuser requested changes
Minor change PT-BR

2021-04-14 12:11 UTC, creed-victor approved these changes

2021-04-14 12:15 UTC, merged