Feat/728 new version check
DistributedCollective/Sovryn-frontend pull request #819
Opened 2021-04-19 14:24 UTC by rick23p

2021-04-19 14:36 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "title": "Sovryn foi atualizado para <br/> <0>Build ID: {{buildId}}</0>",
```suggestion
    "title": "A Sovryn foi atualizada para a versão <br/> <0>Build ID: {{buildId}}</0>",
```

2021-04-19 14:39 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "notice": "Feche todas as guias com o Sovryn aberto para atualizar",
```suggestion
    "notice": "Para atualizar, feche a página da Sovryn ",
```

2021-04-19 14:40 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "closeBtn": "Por favor, deixe-me fechar uma negociação"
```suggestion
    "closeBtn": "Por favor, deixe-me finalizar uma negociação"
```

2021-04-19 14:41 UTC, bitcoinuser requested changes
Changes PT-BR translation

2021-04-20 13:54 UTC, creed-victor requested changes
This should be same design as the modal you did.

<img width="680" alt="Screenshot 2021-04-20 at 16 50 33" src="https://user-images.githubusercontent.com/69458664/115407543-c8ef0100-a1f8-11eb-93fa-cd3406d9de71.png">

Actually, your modal should be moved to this component and just have this extra functionality of checking updates with timer.

Component name:  `ServiceWorkerToaster`

2021-04-20 20:28 UTC, rick23p commented
> This should be same design as the modal you did.
> 
> <img alt="Screenshot 2021-04-20 at 16 50 33" width="680" src="https://user-images.githubusercontent.com/69458664/115407543-c8ef0100-a1f8-11eb-93fa-cd3406d9de71.png">
> 
> Actually, your modal should be moved to this component and just have this extra functionality of checking updates with timer.
> 
> Component name: `ServiceWorkerToaster`

Resolved

2021-04-21 11:00 UTC, creed-victor commented on src/app/components/ServiceWorkerToaster/index.tsx
> +const CHECK_TIME = 10 * 60 * 1000;
```suggestion
const CHECK_TIME = 15e3; // 15 seconds
```

2021-04-21 11:07 UTC, creed-victor commented on src/app/components/ServiceWorkerToaster/index.tsx
> +  alt: 'logo',
Just a dummy change to force redeployment.
```suggestion
  alt: 'Sovryn',
```

2021-04-21 11:08 UTC, creed-victor approved these changes

2021-04-21 11:36 UTC, creed-victor commented on src/index.tsx
> +
```suggestion
```

2021-04-21 11:47 UTC, creed-victor commented on src/app/components/ServiceWorkerToaster/index.module.css
> +}
```suggestion
}

```

2021-04-21 14:12 UTC, creed-victor approved these changes

2021-04-21 14:16 UTC, creed-victor commented on src/app/components/ServiceWorkerToaster/index.tsx
> +
```suggestion
```

2021-04-21 14:24 UTC, t-z-u approved these changes

2021-04-21 14:30 UTC, merged