add note to FastBtcDialog.
DistributedCollective/Sovryn-frontend pull request #925
Opened 2021-04-27 10:15 UTC by rick23p

2021-04-27 13:45 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "note": "Sempre certifique-se de verificar o endereço de depósito BTC conforme FastBTC é atualizado",
```suggestion
    "note": "Verifique sempre se houve mudança no endereço de depósito BTC",
```

2021-04-27 13:46 UTC, bitcoinuser requested changes
Change on PT-BR

2021-04-27 16:46 UTC, creed-victor approved these changes

2021-04-27 16:51 UTC, t-z-u commented
<img width="495" alt="Screenshot 2021-04-27 at 17 49 52" src="https://user-images.githubusercontent.com/79344165/116280928-16cbb200-a781-11eb-836b-3f6fbbcf4075.png">

<img width="505" alt="Screenshot 2021-04-27 at 17 49 46" src="https://user-images.githubusercontent.com/79344165/116280956-1e8b5680-a781-11eb-9e6c-240eef12fce9.png">


It needs to reflect the design spacing more otherwise we end up with a super tall modal
also lets put the close x on the outside like we are wit the other modals

2021-04-27 19:07 UTC, bitcoinuser commented on src/locales/pt_br/translation.json
> +    "note": "Verifique sempre se houve mudança no endereço de depósito BTC",
```suggestion
    "note": "Verifique sempre o endereço de depósito BTC",
```

2021-04-27 19:07 UTC, bitcoinuser requested changes
Change PT-BR

2021-04-28 07:00 UTC, peymannaderi3 commented
> <img alt="Screenshot 2021-04-27 at 17 49 52" width="495" src="https://user-images.githubusercontent.com/79344165/116280928-16cbb200-a781-11eb-836b-3f6fbbcf4075.png">
> 
> <img alt="Screenshot 2021-04-27 at 17 53 33" width="558" src="https://user-images.githubusercontent.com/79344165/116281332-85a90b00-a781-11eb-8fb7-1128d5335eb6.png">
> 
> It needs to reflect the design spacing more otherwise we end up with a super tall modal
> also lets put the close x on the outside like we are wit the other modals
> 
> the link has been updated

Reduced the padding
The close button changes are on redesign branch when they are merge it will be fixed.

2021-04-28 19:18 UTC, merged