Feat/930 liquidity rewards
DistributedCollective/Sovryn-frontend pull request #958
Opened 2021-04-29 07:18 UTC by rick23p

2021-04-29 07:31 UTC, creed-victor requested changes

2021-04-29 07:31 UTC, creed-victor commented on src/app/containers/LiquidityMining/components/RewardPool.tsx
> +  }, [api, props.user]);
- Repeat request every 60 seconds
- Make previous request is canceled when another request starts or component is unmounted

2021-04-29 08:17 UTC, creed-victor approved these changes

2021-04-30 10:32 UTC, merged

2021-05-03 17:26 UTC, cezxx commented
@rick23p  @creed-victor  there is a bug in this feature. When you call the api in RewarPool.tsx you forgot to add '/' before 'amm' which causes a request error .

<img width="505" alt="Zrzut ekranu 2021-05-3 o 19 23 54" src="https://user-images.githubusercontent.com/14337387/116910002-45e09880-ac45-11eb-928f-f43eef0affed.png">